services/listings/ami_charts/AlamedaCountyTCAC2019.json, services/listings/listings/corsairflats.json
Update AMI Chart and corsair listing (waitlist, total units)
=> Update ami chart and corsair listing

services/listings/listings/corsairflats.json
Update application due date for Corsair Flats from 4/10/20 11pm to 4/10/20 4pm
=> Update application due date time

apps/public-ala/package.json, apps/public-sj/package.json, apps/public-smc/package.json
Catch up the three jurisdiction apps to match the latest versions in the public-reference package.json
=> Update app package.jsons to match reference

apps/public-ala/netlify.toml, apps/public-sj/netlify.toml, apps/public-smc/netlify.toml
Just copying the existing format from public-reference
=> Add netlify.toml files to jurisdiction sites

apps/public-ala/package.json, apps/public-ala/page_content/locale_overrides/general.json, apps/public-reference/package.json, package.json, services/listings/package.json, shared/core/package.json, shared/ui-components/package.json, shared/ui-components/src/locales/general.json, shared/ui-components/src/page_components/listing/listing_sidebar/Waitlist.tsx, yarn.lock
=> Update What to Expect text

apps/public-ala/next.config.js, apps/public-ala/package.json, apps/public-sj/next.config.js, apps/public-sj/package.json, apps/public-smc/next.config.js, apps/public-smc/package.json, yarn.lock
This duplicates some work in #38, but I wanted to land just the fixes to make the build work separate from other work.
=> update apps to v0.0.7 and use matching bloom shared packages

apps/public-ala/package.json, apps/public-ala/pages/listing.tsx, apps/public-reference/next.config.js, apps/public-reference/package.json, apps/public-reference/pages/_app.jsx, apps/public-reference/pages/listing.tsx, apps/public-reference/src/customScripts.ts, apps/public-sj/package.json, apps/public-sj/pages/listing.tsx, apps/public-smc/package.json, apps/public-smc/pages/listing.tsx, package.json, services/listings/package.json, services/listings/src/lib/unit_transformations.ts, shared/core/package.json, shared/ui-components/package.json, shared/ui-components/src/helpers/tableSummaries.tsx, shared/ui-components/src/locales/general.json
Merges changes for listings from upstream.
=> Merge core changes

apps/public-ala/pages/_app.jsx, apps/public-ala/src/customScripts.ts, apps/public-sj/pages/_app.jsx, apps/public-sj/src/customScripts.ts, apps/public-smc/pages/_app.jsx, apps/public-smc/src/customScripts.ts
=> add enabling code for GTM to apps

apps/public-smc/layouts/application.tsx, apps/public-smc/page_content/locale_overrides/general.json, apps/public-smc/pages/AdditionalResources.tsx, apps/public-smc/pages/_app.jsx, apps/public-smc/styles/overrides.scss, services/listings/ami_charts/SanMateoHUD2020.json, services/listings/listings/triton.json, services/listings/src/lib/ami_charts.ts, yarn.lock
Fixes #47 when it's done.
I'll leave the AMI charts for @software-project or whoever gets to it, but I wanted to at least get the date updated so it wasn't visually so wrong on the Browse Listings page.
I also updated the site name in the header and moved up to the latest Bloom core packages. There are probably still some other strings to do.
=> Update triton info and SMC QA items

services/listings/listings/bridgepointe.json, shared/ui-components/src/atoms/ApplicationStatus.tsx, shared/ui-components/src/helpers/tableSummaries.tsx, shared/ui-components/src/locales/general.json
=> Fixes for Bridgepointe

services/listings/listings/skylyne.json
Minimal JSON change to extend their deadline per request.
=> Extend the Skylyne application deadline to 6/22/20

apps/public-smc/package.json, services/listings/listings/montara.json, tsconfig.json, yarn.lock
Include all the latest stuff from upstream, plus one minor text change.
=> Final final(?) montara fixes

package.json
I meant to commit this into #87 before I merged it, but I forgot.
=> Minor catch-up for repo root package.json

apps/public-smc/page_content/locale_overrides/general.json, services/listings/listings/montara.json
Currently the easy half of fixes #82.
=> Montara bonus qa

apps/public-ala/page_content/locale_overrides/general.json
Already fixed for SMC upstream, so standardizing on the generic language.
=> Remove ALA custom strings

apps/public-smc/page_content/locale_overrides/general.json
Fixes https://github.com/bloom-housing/bloom/issues/433.
=> Fix Typo on the Additional Opportunities page

services/listings/listings/eastlake.json
for final QA by the property manager.
=> Re-enable eastlake listing for ALA

services/listings/listings/eastlake.json
=> QA fixes for Eastlake

services/listings/ami_charts/AlamedaCountyLIHTC2020.json, services/listings/listings/eastlake.json
just two minor changes (and temporary disabling of Eastlake for the push to production)
=> fix ALA LIHTC AMI chart for Reilly Station

services/listings/listings/jones.json
@bk3c @kathyccheng Fixes for Jones first round of QA. Resolves #116
=> Fixes for Jones QA

services/listings/listings/atlas.json
=> Applicaltion updates for Atlas listing

apps/public-ala/pages/applications/contact/address.tsx, apps/public-ala/pages/applications/financial/income.tsx, apps/public-ala/pages/applications/household/member.tsx, apps/public-ala/pages/applications/review/demographics.tsx, apps/public-ala/src/forms/applications/FormSummaryDetails.tsx
Fixes https://github.com/bloom-housing/bloom/issues/630
=> Hide application questions not used for the Alameda pilot

apps/public-ala/next.config.js
This is just for the workaround until https://github.com/bloom-housing/bloom/issues/631 is fixed.
=> fix reading of SITE_BASE_URL from env vars

apps/public-ala/pages/applications/contact/address.tsx, apps/public-ala/pages/applications/contact/alternate-contact-contact.tsx, apps/public-ala/pages/applications/contact/alternate-contact-name.tsx, apps/public-ala/pages/applications/contact/alternate-contact-type.tsx, apps/public-ala/pages/applications/contact/name.tsx, apps/public-ala/pages/applications/financial/income.tsx, apps/public-ala/pages/applications/financial/vouchers.tsx, apps/public-ala/pages/applications/household/ada.tsx, apps/public-ala/pages/applications/household/add-members.tsx, apps/public-ala/pages/applications/household/current.tsx, apps/public-ala/pages/applications/household/live-alone.tsx, apps/public-ala/pages/applications/household/member.tsx, apps/public-ala/pages/applications/household/members-info.tsx, apps/public-ala/pages/applications/household/preferred-units.tsx, apps/public-ala/pages/applications/preferences/general.tsx, apps/public-ala/pages/applications/preferences/select.tsx, apps/public-ala/pages/applications/reserved/units.tsx, apps/public-ala/pages/applications/review/demographics.tsx, apps/public-ala/pages/applications/review/summary.tsx, apps/public-ala/pages/applications/review/terms.tsx, apps/public-ala/pages/applications/start/choose-language.tsx, apps/public-ala/pages/applications/start/what-to-expect.tsx
Fixes https://github.com/bloom-housing/bloom/issues/653
=> remove the preferences step from the application form header

backend/core/src/auth/auth.controller.ts
Temporary removal of the endpoint for housingbayarea until more of the security model pieces are in place.
=> Remove /auth/register endpoint

backend/core/listing_data/jones.json
Fixes #155
Note: I changed both staging and production DBs directly to avoid a wipe/reload, so this is only for future loads and documentation.
=> phone number fix for Jones

backend/core/listing_data/monarch.json
See https://github.com/housingbayarea/bloom/issues/109#issuecomment-697013542
=> update rentalAssistance text for Monarch

apps/public-ala/pages/listing.tsx
See https://github.com/bloom-housing/bloom/pull/711
=> apply conditional fix for requiredDocuments from upstream

apps/public-ala/layouts/application.tsx, apps/public-ala/page_content/locale_overrides/general.json
Fixes #167.
Note I added another translation field so that we could have text before and after the link. I don't think there's an immediate need to move this upstream since it's pretty specific, but we could certainly do so later if needed.
=> Update ala feedback link

backend/core/listing_data/logan.json
=> Another round of QA fixes for Logan

backend/core/listing_data/logan.json
=> Update Logan leasing agent number

backend/core/ami_charts/AlamedaCountyHCD2020.json, backend/core/listing_data/so-hay.json, backend/core/src/lib/ami_charts.ts
=> Update SoHay, add ami chart

sites/public/next.config.js, sites/public/page_content/AdditionalResources.mdx, sites/public/page_content/AdditionalResourcesSidebar.mdx, sites/public/page_content/locale_overrides/es.json, sites/public/page_content/locale_overrides/vi.json, sites/public/page_content/locale_overrides/zh.json, sites/public/pages/_app.jsx
Alameda Specific Translation on to 0.3 Alameda
=> Add Alameda Specific Translation to 0.3 Alameda

sites/public/pages/index.tsx
Fix for centering hero on Alameda
=> Make hero centered

sites/public/page_content/AdditionalResources.mdx, sites/public/pages/additional-resources.tsx, sites/public/styles/overrides.scss
Requires upstream support: https://github.com/bloom-housing/bloom/pull/1035
=> Improve presentation of the Additional Resources page

sites/public/pages/additional-resources.tsx
I goofed and forgot to include one more commit on #234 — another PR here we gooooo!
=> Fix class names

sites/public/lib/AppSubmissionContext.ts, sites/public/page_content/locale_overrides/es.json, sites/public/page_content/locale_overrides/general.json, sites/public/page_content/locale_overrides/vi.json, sites/public/page_content/locale_overrides/zh.json
Fixes #203, #217, #222, #225, #226
=> Latest translation fixes for Alameda

sites/public/page_content/locale_overrides/general.json, ui-components/src/locales/general.json
https://app.zenhub.com/workspaces/bloom-5dc32d7144bd400001315dac/issues/bloom-housing/bloom/1027
Not sure if this is okay with however we are doing translations :)
=> fix/update error string to not include log-in text

sites/public/page_content/locale_overrides/general.json
=> Application Form: Change "Displaced" to "Displacee"

backend/core/listing_data/so-hay.json
=> Fix So Hay preference format

sites/public/page_content/locale_overrides/general.json, ui-components/src/locales/general.json
=> Lottery translation

backend/core/listing_data/so-hay.json, sites/public/page_content/locale_overrides/es.json, sites/public/page_content/locale_overrides/vi.json, sites/public/page_content/locale_overrides/zh.json
Fixes bloom-housing#1067 for Alameda
=> Fix lottery translations

sites/public/page_content/AdditionalResources.mdx
Closes issue: https://github.com/bloom-housing/bloom/issues/1053
=> Updated 211 translations

backend/core/listing_data/city_center.json
=> QA updates for City Center

backend/core/listing_data/mercy.json
=> Mercy QA updates

sites/public/pages/applications/start/choose-language.tsx
=> Enable sign in on application

backend/core/listing_data/city_center.json, backend/core/listing_data/mercy.json
=> Update paper application links for City Center and Mercy

sites/public/page_content/locale_overrides/es.json
Removed an extra comma from the json file - it occurs problem with build
=> removed extra comma

sites/public/page_content/locale_overrides/vi.json, sites/public/page_content/locale_overrides/zh.json
It's related to: https://github.com/bloom-housing/bloom/issues/1204
=> Updated translations

backend/core/listing_data/alexan.json
=> Alexan QA upates

sites/public/components/RenderIf.tsx
=> Fix multiple language content in Markdown for Alameda

sites/public/page_content/AdditionalResources.mdx
Fixes: https://github.com/bloom-housing/bloom/issues/1799
Preview: https://deploy-preview-370--wonderful-joliot-c00737.netlify.app/
=> Update Alameda Resources Content

sites/public/mdx.d.ts, sites/public/next.config.js, sites/public/package.json, sites/public/page_content/AdditionalResources.md, sites/public/page_content/AdditionalResourcesSidebar.md, sites/public/pages/additional-resources.tsx
also switch page to markdown-to-jsx from mdx
Addresses https://github.com/bloom-housing/bloom/issues/1831
=> feat: update the Additional Resources page content

sites/public/.env.template, sites/public/layouts/application.tsx, sites/public/page_content/locale_overrides/es.json, sites/public/page_content/locale_overrides/general.json, sites/public/page_content/locale_overrides/vi.json, sites/public/page_content/locale_overrides/zh.json, sites/public/page_content/privacy_policy.md
#2183 (Privacy policy updates)
#2122 (Link updates)
Part of #2125 (Custom work in jurisdiction string on application)
Part of #2155 (Medium logo width in SiteHeader)
=> fix(sj): new copy for privacy policy, links

sites/public/layouts/application.tsx, sites/public/page_content/locale_overrides/general.json
Part of #2125 (Customized work in jurisdiction application string)
Part of #2155 (Medium SiteHeader logo width)
=> fix(smc): jurisdictional work string

sites/public/page_content/locale_overrides/general.json
[#2166](https://github.com/bloom-housing/bloom/issues/2166)
Terms copy edit
How Did You Hear jurisdictional website string
On the deploy preview since there are no listings visit these listings for the generic steps:
https://deploy-preview-376--elated-ramanujan-fc6e70.netlify.app/applications/review/demographics
https://deploy-preview-376--elated-ramanujan-fc6e70.netlify.app/applications/review/terms
=> chore: update overrides

sites/public/layouts/application.tsx, sites/public/page_content/locale_overrides/general.json, sites/public/pages/additional-resources.tsx
#2180 Missing footer
#2123 Additional resources copy updates
=> feat: copy updates, footer

sites/public/layouts/application.tsx, sites/public/page_content/AdditionalResourcesSidebar.md, sites/public/page_content/locale_overrides/es.json, sites/public/page_content/locale_overrides/general.json, sites/public/page_content/locale_overrides/vi.json, sites/public/page_content/locale_overrides/zh.json
[#2286](https://github.com/bloom-housing/bloom/issues/2286)
Includes
* Chinese logo title
* Chinese jurisdiction footer
* Chinese Hero header
* Resource page contact section
[#2264](https://github.com/bloom-housing/bloom/issues/2264)
Includes all footer content in all languages
There should be no references to "San Jose County" or "HCD"
=> chore: new strings

sites/public/layouts/application.tsx, sites/public/page_content/AdditionalResources.md, sites/public/page_content/locale_overrides/es.json, sites/public/page_content/locale_overrides/general.json, sites/public/page_content/locale_overrides/vi.json, sites/public/page_content/locale_overrides/zh.json
Resolves https://github.com/bloom-housing/bloom/issues/2284
=> feat: additional resources translations for Alameda

backend/core/src/migration/1650486375189-alameda-programs-and-preferences.ts, sites/public/page_content/locale_overrides/general.json
Updates the migration and translation to address the asks in: https://github.com/bloom-housing/bloom/issues/2623#issuecomment-1108939052
=> fix: updates to migration and translations

sites/public/page_content/how_it_works.md
Addresses #394 
Review the changes on this page: https://deploy-preview-399--wonderful-joliot-c00737.netlify.app/how-it-works
=> chore: update copy on How it Works page

sites/public/page_content/AdditionalResourcesSidebar.md
This PR resolves issue #420 by updating the contact information translations.
This can be tested by going to the public site, clicking the additional resources button, and then changing the language for that page. You should observe the updated translations for each language.
=> fix: updated contact info translations

backend/core/src/migration/1655229223560-san-mateo-2022-ami-charts.ts, backend/core/src/seeder/seeds/ami-charts/sanMateoHUD.ts, backend/core/src/seeder/seeds/ami-charts/sanMateoTCAC.ts
This creates the new ami charts for smc 
issue: https://github.com/housingbayarea/bloom/issues/430
=> feat: creating san mateo ami charts

backend/core/src/applications/applications.controller.ts, backend/core/src/applications/dto/applications-csv-list-query-params.ts, backend/core/types/src/backend-swagger.ts
This PR addresses [#issue](https://github.com/bloom-housing/bloom/issues/1509)
This creates a new application end point that returns a rawMany dump of all applications on a given listing
set up the backend and head to http://localhost:3100/docs/#/ 
there should be a new endpoint `/applications/rawApplicationsList` to play around with
- Either explicitly ask a clarifying question, request changes, or approve the PR if there are …
=> feat: exposing raw many applications endpoint

sites/public/page_content/resources/HowItWorks.md, sites/public/pages/additional-resources.tsx
Closes: https://github.com/housingbayarea/bloom/issues/421
=> feat: create "how it works" section

backend/core/src/application-flagged-sets/application-flagged-sets.service.ts, sites/partners/src/flags/flagSetCols.tsx
brings hotfix over from https://github.com/bloom-housing/bloom/pull/2953
=> fix: fix for big timeout on flagged set (#2946)

backend/core/src/migration/1661805250707-programAndPreferenceUpdates.ts
hba dev deployment for the program/preference clean up
=> hba dev deployment 09/09/2022

sites/public/page_content/how_it_works.md
This PR addresses #467 
Adds a new link in the how it works file.
At the moment we don't have translations that include the separation of the newly linked string, so we cannot update this in other languages until we get those translations. The offline decision was to just add it in English right now.
Check out the how it works page and test out the new link.
- Either explicitly ask a clarifying question, request changes, or …
=> fix: add link to how it works page

.github/workflows/codeql.yml, sites/partners/lib/hooks.ts, sites/partners/page_content/locale_overrides/general.json, sites/partners/pages/listings/[id]/flags/index.tsx, ui-components/src/page_components/NavigationHeader.tsx
=> Merge dev to main

backend/core/src/email/email.service.spec.ts, backend/core/src/email/email.service.ts
=> fix: remove lottery date from confirmation email (#506)

backend/core/src/translations/services/translations.service.ts, sites/public/src/ListingView.tsx
Need to add back in the detail changes we had made here
=> fix: add back in detail page changes

backend/core/CHANGELOG.md, backend/core/package.json, backend/core/src/activity-log/entities/activity-log.entity.ts, backend/core/src/application-flagged-sets/application-flagged-sets-cronjob-boostrap.service.ts, backend/core/src/application-flagged-sets/application-flagged-sets-cronjob-consumer.ts, backend/core/src/application-flagged-sets/application-flagged-sets.module.ts, backend/core/src/listings/listings-cron.service.ts, backend/core/src/listings/listings.module.ts, backend/core/src/listings/listings.service.ts, backend/core/src/migration/1664882024743-add-thank-you-to-email.ts, backend/core/src/migration/1665762602664-remove-activity-log-user-relationship-on-delete.ts, shared-helpers/CHANGELOG.md, shared-helpers/package.json, sites/partners/CHANGELOG.md, sites/partners/cypress/integration/03-listing.spec.ts, sites/partners/package.json, sites/public/CHANGELOG.md, sites/public/package.json, sites/public/pages/applications/financial/income.tsx, sites/public/pages/listings.tsx, sites/public/src/ListingView.tsx, ui-components/CHANGELOG.md, ui-components/__tests__/text/Description.test.tsx, ui-components/package.json, ui-components/src/actions/ExpandableText.stories.tsx, ui-components/src/actions/ExpandableText.tsx, ui-components/src/forms/Field.tsx, ui-components/src/sections/InfoCardGrid.stories.tsx, ui-components/src/text/Description.tsx
=> feat: release 2022-10-25

backend/core/CHANGELOG.md, backend/core/package.json, backend/core/src/activity-log/entities/activity-log.entity.ts, backend/core/src/application-flagged-sets/application-flagged-sets-cronjob-boostrap.service.ts, backend/core/src/application-flagged-sets/application-flagged-sets-cronjob-consumer.ts, backend/core/src/application-flagged-sets/application-flagged-sets.module.ts, backend/core/src/listings/listings-cron.service.ts, backend/core/src/listings/listings.module.ts, backend/core/src/listings/listings.service.ts, backend/core/src/migration/1664882024743-add-thank-you-to-email.ts, backend/core/src/migration/1665762602664-remove-activity-log-user-relationship-on-delete.ts, shared-helpers/CHANGELOG.md, shared-helpers/package.json, sites/partners/CHANGELOG.md, sites/partners/package.json, sites/public/CHANGELOG.md, sites/public/package.json, sites/public/pages/applications/financial/income.tsx, sites/public/pages/listings.tsx, sites/public/src/ListingView.tsx, ui-components/CHANGELOG.md, ui-components/__tests__/text/Description.test.tsx, ui-components/package.json, ui-components/src/actions/ExpandableText.stories.tsx, ui-components/src/actions/ExpandableText.tsx, ui-components/src/forms/Field.tsx, ui-components/src/sections/InfoCardGrid.stories.tsx, ui-components/src/text/Description.tsx
=> feat: release 2022-10-25 (#528)

backend/core/CHANGELOG.md, backend/core/package.json, backend/core/src/activity-log/entities/activity-log.entity.ts, backend/core/src/application-flagged-sets/application-flagged-sets-cronjob-boostrap.service.ts, backend/core/src/application-flagged-sets/application-flagged-sets-cronjob-consumer.ts, backend/core/src/application-flagged-sets/application-flagged-sets.module.ts, backend/core/src/listings/listings-cron.service.ts, backend/core/src/listings/listings.module.ts, backend/core/src/listings/listings.service.ts, backend/core/src/migration/1664882024743-add-thank-you-to-email.ts, backend/core/src/migration/1665762602664-remove-activity-log-user-relationship-on-delete.ts, shared-helpers/CHANGELOG.md, shared-helpers/package.json, sites/partners/CHANGELOG.md, sites/partners/package.json, sites/public/CHANGELOG.md, sites/public/package.json, sites/public/pages/applications/financial/income.tsx, sites/public/pages/listings.tsx, sites/public/src/ListingView.tsx, ui-components/CHANGELOG.md, ui-components/__tests__/text/Description.test.tsx, ui-components/package.json, ui-components/src/actions/ExpandableText.stories.tsx, ui-components/src/actions/ExpandableText.tsx, ui-components/src/forms/Field.tsx, ui-components/src/sections/InfoCardGrid.stories.tsx, ui-components/src/text/Description.tsx
=> feat: release 2022-10-25 (#528) (#529) - smc

backend/core/CHANGELOG.md, backend/core/package.json, backend/core/src/activity-log/entities/activity-log.entity.ts, backend/core/src/application-flagged-sets/application-flagged-sets-cronjob-boostrap.service.ts, backend/core/src/application-flagged-sets/application-flagged-sets-cronjob-consumer.ts, backend/core/src/application-flagged-sets/application-flagged-sets.module.ts, backend/core/src/listings/listings-cron.service.ts, backend/core/src/listings/listings.module.ts, backend/core/src/listings/listings.service.ts, backend/core/src/migration/1664882024743-add-thank-you-to-email.ts, backend/core/src/migration/1665762602664-remove-activity-log-user-relationship-on-delete.ts, shared-helpers/CHANGELOG.md, shared-helpers/package.json, sites/partners/CHANGELOG.md, sites/partners/package.json, sites/public/CHANGELOG.md, sites/public/package.json, sites/public/pages/applications/financial/income.tsx, sites/public/pages/listings.tsx, sites/public/src/ListingView.tsx, ui-components/CHANGELOG.md, ui-components/__tests__/text/Description.test.tsx, ui-components/package.json, ui-components/src/actions/ExpandableText.stories.tsx, ui-components/src/actions/ExpandableText.tsx, ui-components/src/forms/Field.tsx, ui-components/src/sections/InfoCardGrid.stories.tsx, ui-components/src/text/Description.tsx
=> feat: release 2022-10-25 - alameda

backend/core/CHANGELOG.md, backend/core/package.json, backend/core/src/activity-log/entities/activity-log.entity.ts, backend/core/src/application-flagged-sets/application-flagged-sets-cronjob-boostrap.service.ts, backend/core/src/application-flagged-sets/application-flagged-sets-cronjob-consumer.ts, backend/core/src/application-flagged-sets/application-flagged-sets.module.ts, backend/core/src/listings/listings-cron.service.ts, backend/core/src/listings/listings.module.ts, backend/core/src/listings/listings.service.ts, backend/core/src/migration/1664882024743-add-thank-you-to-email.ts, backend/core/src/migration/1665762602664-remove-activity-log-user-relationship-on-delete.ts, shared-helpers/CHANGELOG.md, shared-helpers/package.json, sites/partners/CHANGELOG.md, sites/partners/package.json, sites/public/CHANGELOG.md, sites/public/package.json, sites/public/pages/applications/financial/income.tsx, sites/public/pages/listings.tsx, sites/public/src/ListingView.tsx, ui-components/CHANGELOG.md, ui-components/__tests__/text/Description.test.tsx, ui-components/package.json, ui-components/src/actions/ExpandableText.stories.tsx, ui-components/src/actions/ExpandableText.tsx, ui-components/src/forms/Field.tsx, ui-components/src/sections/InfoCardGrid.stories.tsx, ui-components/src/text/Description.tsx
=> feat: release 2022-10-25 - san-jose

backend/core/src/migration/1666405530762-addSJWhatToExpectTranslations.ts
This PR addresses #491
This PR includes translations for the confirmation email. Other translations are included in PR #522 
Receive a confirmation email — **but** I'm not sure how to hook up the SJ PR to this backend PR
If you have one commit and message, squash. If you need …
=> chore: add SJ confirmation email translations

backend/core/src/migration/1666583981588-multiselectTranslationFix.ts
This deploys the migration fix for the multiselect translation issue: https://github.com/housingbayarea/bloom/pull/523
=> fix: migration to fix multiselect translation bug

backend/core/src/multiselect-question/entities/multiselect-question.entity.ts, backend/core/src/multiselect-question/multiselect-question.controller.ts, backend/core/src/multiselect-question/types/multiselect-option.ts, backend/core/src/translations/services/translations.service.ts, backend/core/types/src/backend-swagger.ts, sites/public/lib/helpers.tsx, sites/public/pages/applications/review/terms.tsx
This is the deployment pr for the interim fix on multiselect questions
=> fix: multiselect question x translation issue

backend/core/package.json, yarn.lock
=> fix: upgrade ioredis version (#3161)

backend/core/src/applications/services/csv-builder.service.ts, backend/core/src/applications/services/csv-builder.spec.ts, backend/core/src/migration/1666583981588-multiselectTranslationFix.ts
This PR addresses [#issue](https://github.com/bloom-housing/bloom/issues/3138)
This fixes the migration script so that it runs again after a program translation got some updates from google. 
This also fixes the problem of commas in the headers of the csv 
Pull down the latest copy of production data, aim your local at that copy and run the migration
test the csv export for the `Park Alameda` listing
also verify that the csv export looks correct on a listing with a , in one of the headers
- Also review the acceptance criteria on the Netlify deploy preview (noting that …
=> fix: updates per kathy finds

backend/core/src/applications/services/csv-builder.service.ts, backend/core/src/applications/services/csv-builder.spec.ts, backend/core/src/migration/1666583981588-multiselectTranslationFix.ts
* fix: updates per kathy finds
* fix: updates per morgan
* fix: update per emily
- Also review the acceptance criteria on the Netlify deploy preview (noting that these do not yet include any backend …
=> fix: add new translation to migration and fix comma in export (#545)

backend/core/src/applications/applications.controller.ts, backend/core/src/auth/controllers/user.controller.ts, backend/core/src/listings/listings.controller.ts, sites/partners/lib/hooks.ts
This is a cherry-pick of https://github.com/bloom-housing/bloom/pull/3172
=> feat: adding UUID validation

backend/core/src/migration/1666583981588-multiselectTranslationFix.ts
A few programs/preferences got their google generated translations updated (google improved their translations into Chinese again). This is a pr to address those new updates
Pull down the most recent backup of hba prod
stand it up on your local box
run the migration
everything should work as expected
- Either explicitly ask a clarifying question, request changes, or approve the PR if there are small remaining changes but the PR …
=> fix: migration update

sites/public/page_content/jurisdiction_overrides/san_jose/resources/homelessHotline.md
This PR addresses #527
This PR updates some text on one of San Jose's resource cards.
Ensure the card text matches the changes requested in the issue.
=> fix: updates to a san jose resource card

shared-helpers/src/AuthContext.ts, sites/public/src/ConfirmationModal.tsx
This PR addresses #[issue ](https://github.com/housingbayarea/bloom/issues/566)
There was an issue where when a user is trying to confirm their account on the public site, they were running into a problem where there account was never getting confirmed. This meant that they were never logging in even though they clicked the confirmation link on the email.
This is a fix to resolve that so when following the confirmation link they will be logged in 
head over to the public site ( https://hba-public-dev.netlify.app/ )
attempt to create a new account
get the email 
click the confirmation link
you should now be signed in
- Pull the changes down …
=> fix: public site user confirmation issue

sites/public/src/translations.ts
This adds the Tagalog translation for the specific jurisdiction (such as Alameda)
If you have one commit and …
=> fix: support tagalog jurisdiction translations

sites/public/page_content/jurisdiction_overrides/san_mateo/resources/BayArea211.md
This PR addresses #570
added call 211 with translations
Go to `/additional-resources` (http://localhost:3000/additional-resources) should be visible in other resources section
=> feat: add call 211 to resource card

sites/public/src/page_content/jurisdiction_overrides/alameda/resources/adobeServicesEast.md, sites/public/src/page_content/jurisdiction_overrides/alameda/resources/adobeServicesSouth.md, sites/public/src/page_content/jurisdiction_overrides/alameda/resources/baCommunityServiceHayward.md, sites/public/src/page_content/jurisdiction_overrides/alameda/resources/baCommunityServiceNorth.md, sites/public/src/page_content/jurisdiction_overrides/alameda/resources/buildingFuturesAlameda.md, sites/public/src/page_content/jurisdiction_overrides/alameda/resources/buildingFuturesSanLeandro.md, sites/public/src/page_content/jurisdiction_overrides/alameda/resources/eastCountyHeader.md, sites/public/src/page_content/jurisdiction_overrides/alameda/resources/fremontFamily.md, sites/public/src/page_content/jurisdiction_overrides/alameda/resources/haAlamedaCity.md, sites/public/src/page_content/jurisdiction_overrides/alameda/resources/haAlamedaCounty.md, sites/public/src/page_content/jurisdiction_overrides/alameda/resources/haBerkley.md, sites/public/src/page_content/jurisdiction_overrides/alameda/resources/haLivermore.md, sites/public/src/page_content/jurisdiction_overrides/alameda/resources/haOakland.md, sites/public/src/page_content/jurisdiction_overrides/alameda/resources/keepOaklandHoused.md, sites/public/src/page_content/jurisdiction_overrides/alameda/resources/midCountyHeader.md, sites/public/src/page_content/jurisdiction_overrides/alameda/resources/northCountyHeader.md, sites/public/src/page_content/jurisdiction_overrides/alameda/resources/southCountyHeader.md, sites/public/src/page_content/jurisdiction_overrides/alameda/resources/womensDropInCenter.md, sites/public/src/page_content/jurisdiction_overrides/san_mateo/resources/BayArea211.md, sites/public/src/page_content/jurisdiction_overrides/san_mateo/resources/SMCHousingSearch.md
On the additional resources page for Spanish in Alameda there were several spots where markdown styling wasn't getting picked up. This is a follow up to #590 for the missed spots. The Markdown files can no longer have a new line after the `<RenderIf>`.
Also fixed Spanish and Vietnamese for the 211 heading on San Mateo.
Additionally changed the url for smc housing search as brought up here https://exygy.slack.com/archives/C02G1S19QA2/p1675889571034389
Go to the /additional-resources page and test all languages
- Also review the …
=> fix: spanish fixes for san mateo and alameda

backend/core/src/applications/entities/application-multiselect-question.entity.ts, backend/core/src/applications/types/application-multiselect-question-option.ts, backend/core/src/multiselect-question/multiselect-question.controller.ts, backend/core/types/src/backend-swagger.ts, sites/partners/cypress/fixtures/listing.json, sites/partners/cypress/integration/03-listing.spec.ts
This is a cherry-pick of https://github.com/bloom-housing/bloom/pull/3376 to act as a hotfix 
resolve the issue laid out in: https://github.com/housingbayarea/bloom/issues/606
=> fix: program/preference keys length uncap (#3376)

backend/core/src/applications/services/applications.service.ts, shared-helpers/src/locales/general.json, sites/public/src/pages/account/edit.tsx, sites/public/src/pages/applications/contact/address.tsx, sites/public/src/pages/applications/contact/alternate-contact-contact.tsx, sites/public/src/pages/applications/contact/alternate-contact-name.tsx, sites/public/src/pages/applications/contact/alternate-contact-type.tsx, sites/public/src/pages/applications/contact/name.tsx, sites/public/src/pages/applications/household/member.tsx, sites/public/src/pages/create-account.tsx
Pull over the bug fix from core:
* 9d96cef0a - fix: frontend validation for char max (#3413) <Emily Jablonski>
=> fix: frontend validation for char max (#3413)

sites/public/src/page_content/jurisdiction_overrides/san_jose/resources/housingChoices.md, sites/public/src/page_content/jurisdiction_overrides/san_mateo/resources/HousingChoices.md
This PR addresses #3501
added links for resource card
for San Mateo and San Jose check Housing Choices resource card for proper links
=> fix: update links for housing choices resource card

backend/core/src/applications/applications.controller.ts, backend/core/src/applications/dto/applications-csv-list-query-params.ts, backend/core/src/applications/helpers.ts, backend/core/src/applications/services/application-csv-exporter.service.ts, backend/core/test/lib/format-local-date.spec.ts, backend/core/types/src/backend-swagger.ts, sites/partners/src/components/applications/ApplicationsColDefs.ts, sites/partners/src/components/applications/PaperApplicationDetails/sections/DetailsApplicationData.tsx, sites/partners/src/components/flags/applicationsCols.tsx, sites/partners/src/lib/helpers.ts, sites/partners/src/lib/hooks.ts, sites/partners/src/pages/application/[id]/applicationsCols.tsx
This PR addresses #3518
This PR is cherry-picked from #3526 and displays the application submission date in the user's local time on both the partner's table along with the application export. 
This can be tested locally by ensuring that the time for electronic submissions is displayed the same on the partner's table in addition to the export.
Additionally, the two screenshots below outline the DB responses seen on dev and I added testing that directly mirrors these responses to demonstrate this approach's effectiveness.
- Also review the acceptance criteria on the …
=> fix: timezone cherry pick from core

sites/public/src/lib/helpers.tsx
This PR addresses #3679
Quick fix for download not working in chrome
Ensure paper application download works in chrome
=> fix: add target

backend/core/src/migration/1697654611220-turn-on-listing-approval.ts
This PR addresses https://github.com/metrotranscom/doorway/issues/298
The plan is to turn on the listing approval feature on October 25th. This PR adds the admin and jurisdictionAdmin role to the listing approval permission array for all Housing Bay Area jurisdictions. I will also be creating a migration for Doorway
It is recommended that you reseed before you pull down this change and then run the migrations. That way it will simulate the real flow.
- Also review the acceptance criteria on the Netlify deploy preview (noting that these do not yet include any backend …
=> fix: add migration to add listing approval permissions

sites/public/src/pages/applications/review/summary.tsx
This will let the verify endpoint errors get caught by sentry
You can put an error in the verify endpoint so that when it fails attempting to submit an application will both get you to go back through the application and also throw an error 
If you have …
=> feat: throwing error so verify is caught by sentry

sites/public/src/lib/applications/AppSubmissionContext.ts, sites/public/src/lib/applications/ApplicationConductor.ts, sites/public/src/pages/_app.tsx, sites/public/src/pages/applications/contact/address.tsx, sites/public/src/pages/applications/contact/alternate-contact-contact.tsx, sites/public/src/pages/applications/contact/alternate-contact-name.tsx, sites/public/src/pages/applications/contact/alternate-contact-type.tsx, sites/public/src/pages/applications/contact/name.tsx, sites/public/src/pages/applications/financial/income.tsx, sites/public/src/pages/applications/financial/vouchers.tsx, sites/public/src/pages/applications/household/ada.tsx, sites/public/src/pages/applications/household/add-members.tsx, sites/public/src/pages/applications/household/changes.tsx, sites/public/src/pages/applications/household/live-alone.tsx, sites/public/src/pages/applications/household/member.tsx, sites/public/src/pages/applications/household/preferred-units.tsx, sites/public/src/pages/applications/household/student.tsx, sites/public/src/pages/applications/start/autofill.tsx
To repro, on the income step of the application, enter a currency amount but don't select a period and try to continue to the next page. On application confirmation you'll get the verify error.
=> fix: verify application errors

sites/public/src/page_content/jurisdiction_overrides/san_mateo/resources/HavenConnect.md
This PR addresses https://github.com/bloom-housing/bloom/issues/3864
This PR updates the link on a SMC resource card. The existing link seems to redirect anyway, so the prod behavior will seem as though it's already set to the new link.
If you have one commit and message, …
=> fix: update link on smc resource card

backend/core/src/listings/listings.controller.ts, backend/core/types/src/backend-swagger.ts
This PR addresses [#issue](https://github.com/bloom-housing/bloom/issues/3779)
This creates a new endpoint 
you can test via the localhost:3100/docs site
=> feat: creating external listing "stub" for doorway usage

backend/core/src/auth/services/user.service.ts
=> fix: limit the characters for name on user

api/src/services/user.service.ts
carries: https://github.com/bloom-housing/bloom/pull/3932
user create/update fixes
=> fix: user update/create fixes (#3932)

sites/public/tailwind.config.js
This PR addresses #422 previously made here: https://github.com/metrotranscom/doorway/pull/479 but needs to be in hba and core
This is a follow-up which supports tailwind loading from the Account Card in shared helpers.
This can be tested by running yarn build / yarn start in sites/public and the sign-in page styling should show as expected. Specifically, there should be margin around the create account header and buttons on the sign-in page
- Also review the acceptance criteria on the Netlify deploy preview (noting that these do not yet include any backend changes …
=> fix: shared helpers loading tailwind

sites/public/next.config.js
This PR addresses #3911
The adds doorwayUrl back to the next config file so the footer links work again.
Run this locally and see that the footer links work again
=> fix: add doorwayUrl back to next config

api/src/services/application-flagged-set.service.ts, api/test/unit/services/application-flagged-set.service.spec.ts
pulls fix for https://github.com/bloom-housing/bloom/issues/3954 across
=> fix: afs needs to be paginating (#3955)

sites/public/src/layouts/application.module.scss, sites/public/src/layouts/application.tsx, sites/public/src/page_content/jurisdiction_overrides/alameda/locale_overrides/es.json, sites/public/src/page_content/jurisdiction_overrides/alameda/locale_overrides/general.json, sites/public/src/page_content/jurisdiction_overrides/alameda/locale_overrides/tl.json, sites/public/src/page_content/jurisdiction_overrides/alameda/locale_overrides/vi.json, sites/public/src/page_content/jurisdiction_overrides/alameda/locale_overrides/zh.json
This PR addresses #3958
This PR adds the requested banner by Alameda.
This can be tested by updating the maintenance window env to include the current time and testing each of the languages to display the correct banner. Also, change the jurisdiction env and rebuild, and the banner will not be visible.
- Either explicitly ask a clarifying question, request changes, or approve the PR if there are small remaining changes but the …
=> fix: haca banner

api/.env.template, api/prisma/migrations/09_update_submission_date_on_applications/migration.sql, api/prisma/seed-helpers/application-factory.ts, api/prisma/seed-staging.ts, api/src/dtos/applications/application-csv-query-params.dto.ts, api/src/dtos/listings/listing-csv-query-params.dto.ts, api/src/services/application-csv-export.service.ts, api/src/services/listing-csv-export.service.ts, api/test/unit/services/application-csv-export.service.spec.ts, shared-helpers/src/types/backend-swagger.ts, sites/partners/src/components/applications/ApplicationsColDefs.ts, sites/partners/src/components/applications/PaperApplicationDetails/sections/DetailsApplicationData.tsx, sites/partners/src/lib/applications/formatApplicationData.ts, sites/partners/src/lib/helpers.ts, sites/partners/src/lib/hooks.ts, sites/partners/src/pages/application/[id]/applicationsCols.tsx, sites/partners/src/pages/listings/[id]/applications/index.tsx
Releasing 
- https://github.com/bloom-housing/bloom/pull/3980 (Jurisdictional admins should always be able to see demographic information on application exports)
- https://github.com/bloom-housing/bloom/pull/3959 (timezones in export)
=> Release: 04-02-2024

sites/public/src/page_content/jurisdiction_overrides/san_jose/how_it_works.md
This PR addresses #4000
This PR fixes a typo in a link on the how it works page for San Jose.
Run San Jose's site locally and go to http://localhost:3000/how-it-works, expand the eligibility section, and click "Tables for San José are provided here."
If you have one commit and …
=> fix: correct link typo

api/src/services/application.service.ts
This PR addresses #4060 
Previously, the dto was being passed which doesn't include the confirmationCode. Passing the mappedApplication resolves this.
This can be tested by filling out an application with an email and ensuring the application confirmation email comes through correctly with a confirmation code.
- Either explicitly ask a clarifying question, request changes, or approve the PR if there are small remaining changes …
=> fix: pass mappedApplication (#4061)

README.md, sites/public/src/page_content/jurisdiction_overrides/alameda/locale_overrides/es.json, sites/public/src/page_content/jurisdiction_overrides/alameda/locale_overrides/general.json, sites/public/src/page_content/jurisdiction_overrides/alameda/locale_overrides/tl.json, sites/public/src/page_content/jurisdiction_overrides/alameda/locale_overrides/vi.json, sites/public/src/page_content/jurisdiction_overrides/alameda/locale_overrides/zh.json
=> fix: change maintenance string

sites/public/src/layouts/application.tsx
=> fix: allow maintenance mode in all jurisdictions

sites/public/src/lib/hooks.ts, sites/public/src/pages/index.tsx
Release to hba of: https://github.com/bloom-housing/bloom/pull/4096
=> fix: restores getStaticProps functionality (#4096)

api/prisma/migrations/20240520173759_application_user_id_index/migration.sql, api/prisma/schema.prisma
This releases: https://github.com/bloom-housing/bloom/pull/4098 (new application index on user id)
=> feat: new application index on user_id (#4098)

sites/public/src/page_content/jurisdiction_overrides/alameda/locale_overrides/es.json, sites/public/src/page_content/jurisdiction_overrides/alameda/locale_overrides/general.json, sites/public/src/page_content/jurisdiction_overrides/alameda/locale_overrides/tl.json, sites/public/src/page_content/jurisdiction_overrides/alameda/locale_overrides/vi.json, sites/public/src/page_content/jurisdiction_overrides/alameda/locale_overrides/zh.json
This PR addresses #4020
Updates income question for AC
Fill application, income question for AC should be updated
=> fix: add income translation overwrite for alameda

api/.env.template, api/prisma/migrations/11_add_script_runs/migration.sql, api/prisma/migrations/12_add_script_runner_translations/migration.sql, api/prisma/schema.prisma, api/prisma/seed-helpers/translation-factory.ts, api/src/controllers/auth.controller.ts, api/src/controllers/script-runner.controller.ts, api/src/dtos/script-runner/bulk-application-resend.dto.ts, api/src/dtos/script-runner/data-transfer.dto.ts, api/src/modules/app.module.ts, api/src/modules/script-runner.module.ts, api/src/services/email.service.ts, api/src/services/script-runner.service.ts, api/src/views/script-runner.hbs, api/test/unit/services/app.service.spec.ts, api/test/unit/services/script-runner.service.spec.ts, shared-helpers/src/types/backend-swagger.ts
releases script runner for hba
=> Release: HBA release script runner

shared-helpers/src/utilities/formKeys.ts, sites/partners/src/components/applications/PaperApplicationForm/sections/FormDemographics.tsx, sites/public/src/pages/applications/review/demographics.tsx
Release https://github.com/bloom-housing/bloom/pull/4102
Flow 1: Go through public site online application flow
Flow 1a: Select Asian, select a suboption of Asian, select Native Hawaiian, unselect Native Hawaiian, confirm original selections are still present.
Flow 1b: Make selections, click the Next button, click the Back button, confirm original selections are still present.
complete flow and submit.
Flow 2: Login to the partners side, navigate to an open listing, go to the Applications tab
Flow 2a: select Add Application, complete required fields, select Asian, select a suboption of Asian, select Native Hawaiian, unselect Native Hawaiian, confirm original selections are still present, submit.
Flow 2b: select an …
=> release: Demographics Race Field Render Issue

docs/pull_request_template.md
Pulls over https://github.com/bloom-housing/bloom/pull/4116 from core
=> docs: release - updated pr template (#4116)

sites/partners/src/components/listings/PaperListingDetails/DetailsUnitDrawer.tsx, sites/partners/src/components/listings/PaperListingDetails/sections/DetailApplicationDates.tsx, sites/partners/src/components/listings/PaperListingDetails/sections/DetailUnits.tsx, sites/partners/src/components/listings/PaperListingForm/OpenHouseForm.tsx, sites/partners/src/components/listings/PaperListingForm/index.tsx, sites/partners/src/components/listings/PaperListingForm/sections/ApplicationDates.tsx, sites/partners/src/components/listings/PaperListingForm/sections/ApplicationTypes.tsx, sites/partners/src/components/listings/PaperListingForm/sections/BuildingSelectionCriteria.tsx, sites/partners/src/components/listings/PaperListingForm/sections/ListingPhotos.tsx, sites/partners/src/components/listings/PaperListingForm/sections/LotteryResults.tsx, sites/partners/src/components/listings/PaperListingForm/sections/SelectAndOrder.tsx, sites/partners/src/components/listings/PaperListingForm/sections/Units.tsx, sites/partners/src/components/settings/PreferenceDrawer.tsx, sites/partners/src/pages/application/[id]/review.tsx
This PR includes the following Core PRs:
* https://github.com/bloom-housing/bloom/pull/4118
* https://github.com/bloom-housing/bloom/pull/4129
=> release: fix buttons and other elements from design QA

api/src/controllers/script-runner.controller.ts, api/src/dtos/script-runner/ami-chart-import.dto.ts, api/src/modules/script-runner.module.ts, api/src/services/script-runner.service.ts, api/test/unit/services/script-runner.service.spec.ts, shared-helpers/src/types/backend-swagger.ts
this releases https://github.com/bloom-housing/bloom/pull/4125 to HBA (ami chart import script runner script)
=> feat: ami chart import script runner (#4125)

api/src/services/listing.service.ts, api/test/integration/listing.e2e-spec.ts, sites/partners/src/components/listings/ListingFormActions.tsx, sites/partners/src/components/listings/PaperListingForm/sections/ApplicationAddress.tsx, sites/partners/src/lib/listings/AdditionalMetadataFormatter.ts, sites/partners/src/lib/listings/BooleansFormatter.ts, sites/partners/src/pages/listings/[id]/index.tsx
* 5566bf797 - fix: add error message for incorrect listing approval (#4134)
* 75ed4d834 - fix: allow removal of mailing address (#4130)
=> fix: mailing address fix

api/src/services/application-flagged-set.service.ts, api/src/services/listing.service.ts, api/test/unit/services/application-csv-export.service.spec.ts, api/test/unit/services/application-flagged-set.service.spec.ts, api/test/unit/services/listing.service.spec.ts
Pulls the following commit from core:
* fix: add the ability to disconnect community types
=> fix: add the ability to disconnect community types (#4153)

sites/partners/src/components/shared/NavigationHeader.tsx, sites/partners/src/pages/listings/[id]/applications/index.tsx, sites/partners/src/pages/listings/[id]/applications/pending/index.tsx, sites/partners/src/pages/listings/[id]/lottery.tsx, sites/public/package.json, yarn.lock
Pulls in the following commit from core:
https://github.com/bloom-housing/bloom/pull/4162
=> fix: lottery rebase issues (#4162)

sites/public/src/pages/applications/contact/address.tsx, sites/public/src/pages/applications/household/member.tsx
The PR contains the Core PR: https://github.com/bloom-housing/bloom/pull/4175
=> release: use the correct error keys for State and Zip

sites/public/src/pages/applications/review/confirmation.tsx, sites/public/styles/overrides.scss
This PR contains Core PR: https://github.com/bloom-housing/bloom/pull/4173
=> release: application confirmation styling updates based on design QA

sites/partners/src/components/listings/PaperListingForm/sections/LotteryResults.tsx
Releases https://github.com/bloom-housing/bloom/commit/cd8b6a091e8d319497e8615668d9041997629bcb to HBA
=> fix: allows uploading lottery result update (#4295)

api/prisma/migrations/16_lottery_total/migration.sql, api/prisma/schema.prisma, api/src/controllers/lottery.controller.ts, api/src/dtos/applications/application-lottery-total.dto.ts, api/src/dtos/listings/listing-update.dto.ts, api/src/dtos/listings/listing.dto.ts, api/src/dtos/lottery/lottery-public-total.dto.ts, api/src/services/lottery.service.ts, api/test/integration/lottery.e2e-spec.ts, api/test/unit/services/google-translate.service.spec.ts, api/test/unit/services/lottery.service.spec.ts, shared-helpers/src/types/backend-swagger.ts, sites/partners/__tests__/lib/helpers.test.ts, sites/partners/cypress/e2e/default/03-listing.spec.ts, sites/partners/cypress/e2e/default/09-lottery.spec.ts, sites/partners/cypress/e2e/listings-approval/listings-approval.spec.ts, sites/partners/cypress/support/commands.js, sites/partners/cypress/support/index.d.ts, sites/partners/src/components/listings/PaperListingForm/sections/RankingsAndResults.tsx, sites/partners/src/lib/helpers.ts, sites/partners/src/lib/listings/formTypes.ts, sites/public/src/pages/account/application/[id]/lottery-results.tsx
Pulls over the following commits from core
=> feat: lottery totals data, date formatting, flaky cypress

api/src/services/listing.service.ts, api/test/integration/listing.e2e-spec.ts, api/test/unit/services/listing.service.spec.ts
releases: https://github.com/bloom-housing/bloom/commit/6350344edbbb40509c00b323d7d5fdbbc6cc617f
=> fix: saving listing with uploaded lottery (#4277)

api/src/services/application-exporter.service.ts
Releases: https://github.com/bloom-housing/bloom/pull/4329
=> feat: switching to write stream and sequential building (#4329)

api/src/services/application-flagged-set.service.ts, api/test/integration/application-flagged-set.e2e-spec.ts, api/test/unit/services/application-flagged-set.service.spec.ts
Pulls over [fix: tighten the rules for which afs job](https://github.com/housingbayarea/bloom/commit/13c86a4be224dcd81724214d3ecaabfb44aebb85) from Core
=> fix: tighten the rules for which afs job (#4366)

api/src/main.ts, api/src/services/application-exporter.service.ts, api/src/utilities/custom-exception-filter.ts, api/test/unit/services/application-exporter.service.spec.ts, api/test/unit/utilities/custom-exception-filter.spec.ts
Releases https://github.com/bloom-housing/bloom/pull/4362
=> fix: if programs is null no longer errors (#4362)

api/prisma/migrations/18_copy_of_reference/migration.sql, api/prisma/schema.prisma, api/src/services/listing-csv-export.service.ts, api/src/services/listing.service.ts, api/test/integration/listing.e2e-spec.ts, api/test/unit/services/listing.service.spec.ts
This PR addresses [#(806)](https://github.com/metrotranscom/doorway/issues/806)
Releases: https://github.com/bloom-housing/bloom/pull/4375
Run partner portal and api and login as a admin user.
Have the listing id for the listing you would like to duplicate.
Fill out the payload for listings/duplicate. Set storedListing.id to the above.
Click the listing export button in the parter portal.
Open the listing csv and view/verify the new columns.
- Either (1) explicitly ask a clarifying question, (2) request changes, or (3) approve the PR, even if there are very small remaining changes, if you …
=> release: record of listing copy (#4375)

api/src/services/application.service.ts, api/src/services/email.service.ts, api/src/services/listing.service.ts, api/src/services/lottery.service.ts, api/test/integration/lottery.e2e-spec.ts, api/test/unit/services/application.service.spec.ts, api/test/unit/services/lottery.service.spec.ts, shared-helpers/src/types/backend-swagger.ts, sites/public/__tests__/components/applications/StatusItem.test.tsx, sites/public/src/components/account/StatusItem.tsx, sites/public/src/components/account/StatusItemWrapper.tsx
Pulls over the below commits from core
=> feat: lottery duplicates, email fixes

sites/public/cypress/support/commands.js, sites/public/src/components/shared/FormSummaryDetails.tsx, sites/public/src/pages/applications/household/add-members.tsx
Pulls in Core:
* bloom-housing/bloom#4385
=> fix: household members link on application review (#4385)

api/package.json
releases: https://github.com/bloom-housing/bloom/pull/4388
=> fix: may the force be with you (#4388)

api/src/dtos/users/confirmation-request.dto.ts, api/test/integration/application.e2e-spec.ts, api/test/integration/listing.e2e-spec.ts, api/test/integration/lottery.e2e-spec.ts, api/test/integration/permission-tests/permission-as-admin.e2e-spec.ts, api/test/integration/permission-tests/permission-as-juris-admin-correct-juris.e2e-spec.ts, api/test/integration/permission-tests/permission-as-juris-admin-wrong-juris.e2e-spec.ts, api/test/integration/permission-tests/permission-as-no-user.e2e-spec.ts, api/test/integration/permission-tests/permission-as-partner-correct-listing.e2e-spec.ts, api/test/integration/permission-tests/permission-as-partner-wrong-listing.e2e-spec.ts, api/test/integration/permission-tests/permission-as-public.e2e-spec.ts, api/test/integration/user.e2e-spec.ts, api/test/unit/services/auth.service.spec.ts
This PR addresses  [#(4361)](https://github.com/bloom-housing/bloom/issues/4361)
Release: https://github.com/bloom-housing/bloom/pull/4389/
Run e2e tests locally.
=> release: flaky backend tests (#4389)

api/src/services/application.service.ts
Releases: https://github.com/bloom-housing/bloom/pull/4401
=> feat: exposes pref unit type (#4401)

sites/public/.env.template, sites/public/next.config.js, sites/public/src/lib/hooks.ts
Releases: https://github.com/bloom-housing/bloom/pull/4402
=> fix: exposing more closed listings (#4402)

api/src/controllers/auth.controller.ts, api/src/controllers/lottery.controller.ts, api/src/controllers/script-runner.controller.ts, api/test/integration/custom-exception-filter.e2e-spec.ts
releases: https://github.com/bloom-housing/bloom/pull/4374
=> fix: applying pass key to endpoints that were missing it (#4374)

api/src/services/listing-csv-export.service.ts
This PR addresses https://github.com/bloom-housing/bloom/issues/4470
This updates the GenAI export endpoint. Adding ami chart overrides and changes the units that get exported with this
Provide instructions so we can review, including any needed configuration, and the test cases that need to be QAd.
=> feat: gen ai endpoint units updates

sites/partners/src/page_content/locale_overrides/general.json
This PR addresses #4446
release of minor copy change for retract ([this PR](https://github.com/bloom-housing/bloom/pull/4468))
Provide instructions so we can review, including any needed configuration, and the test cases that need to be QAd.
=> fix: update retract modal copy (#4468)

api/src/services/listing-csv-export.service.ts
Addresses: https://github.com/bloom-housing/bloom/issues/4470
- adds a multiselect question csv export to the zip
- adjust csv headers to be more sql like (lower case, `_` instead of ` `)
- adjusts the columns in the listing export to be the columns laid out in the spreadsheet
=> feat: adding msq export, updating listing export for gen ai

api/prisma/migrations/20_create_feature_flag_table/migration.sql, api/prisma/schema.prisma
This PR addresses [#(1287)](https://github.com/bloom-housing/bloom/issues/1287)
Creates new feature flag table with desired fields.
Run migrations locally. Open query and insert a record into the table.
=> feat: create feature flag table (#4475)

api/src/controllers/application.controller.ts, api/src/controllers/lottery.controller.ts, api/src/services/application-exporter.service.ts, api/src/utilities/zip-export.ts, api/test/unit/services/application-exporter.service.spec.ts, sites/partners/src/lib/hooks.ts, sites/partners/src/pages/api/adapter/[...backendUrl].ts, sites/partners/src/pages/listings/[id]/applications/index.tsx, sites/partners/src/pages/listings/[id]/lottery.tsx
This PR addresses [#(4370)](https://github.com/bloom-housing/bloom/issues/4370)
This PR adds a helper function to sort listings preferences based on the ordinal position prior to generating a spreadsheet with tabs for each relevant set of applications. [#(4464)](https://github.com/bloom-housing/bloom/pull/4464)
Generalized zip exporting code to allow for applications export to be zipped. [#(4588)](https://github.com/bloom-housing/bloom/pull/4588)
With a listing that has applications, go to the applications tab.
Export the applications.
Confirm export was a zip file.
Open zip file, confirm csv is created.
Open CSV file and check contents.
Edit listing to be a lottery.
Listing should have multiple preferences.
Run lottery.
Export lottery.
Confirm export was a zip file.
Open zip file, …
=> release: refactor and extend zip code

sites/public/src/layouts/max-width.module.scss, sites/public/src/layouts/max-width.tsx, sites/public/src/pages/404.tsx, sites/public/src/pages/_error.tsx
=> refactor: max width layout (#4500)

api/test/integration/listing.e2e-spec.ts
Releases the flaky test fix: https://github.com/bloom-housing/bloom/pull/4743
=> fix: flaky test updates (#4743)

api/prisma/seed-staging.ts, api/src/dtos/feature-flags/feature-flag.dto.ts, api/src/services/listing-csv-export.service.ts, api/test/integration/listing.e2e-spec.ts, shared-helpers/src/locales/general.json, shared-helpers/src/types/backend-swagger.ts, sites/partners/src/components/listings/PaperListingDetails/sections/DetailAdditionalFees.tsx, sites/partners/src/components/listings/PaperListingDetails/sections/DetailBuildingFeatures.tsx, sites/partners/src/components/listings/PaperListingDetails/sections/DetailUnits.tsx, sites/partners/src/components/listings/PaperListingForm/sections/AdditionalFees.tsx, sites/partners/src/components/listings/PaperListingForm/sections/BuildingFeatures.tsx, sites/partners/src/components/listings/PaperListingForm/sections/Units.tsx, sites/public/__tests__/pages/sign-in.test.tsx, sites/public/src/components/listing/ListingView.tsx, sites/public/src/lib/helpers.tsx
Pulls the following commits over from core:
* fix: add utilities included and accessibility to csv (#4612)
* test: sign-in page integration test  (#4623)
* [fix: update listing e2e test to be more determinant (](https://github.com/housingbayarea/bloom/pull/846/commits/60e1f61e7b2233e5e9312ce7db87a8a55eae864c)https://github.com/bloom-housing/bloom/pull/4673[)](https://github.com/housingbayarea/bloom/pull/846/commits/60e1f61e7b2233e5e9312ce7db87a8a55eae864c)
=> Release: 2025-03-05

api/prisma/seed-helpers/listing-data/lakeview-villa.ts, api/prisma/seed-staging.ts, api/src/enums/feature-flags/feature-flags-enum.ts, shared-helpers/src/types/backend-swagger.ts, sites/partners/__tests__/pages/listings/[id]/index.test.tsx, sites/partners/src/components/listings/PaperListingDetails/sections/DetailApplicationTypes.tsx, sites/partners/src/components/listings/PaperListingForm/sections/ApplicationTypes.tsx
This contains the core PR:
* bloom-housing/bloom#4791
=> release: add feature flag for disabling common app (#4791)

api/.env.template, api/package.json, api/src/controllers/auth.controller.ts, api/src/dtos/auth/login.dto.ts, api/src/passports/single-use-code.strategy.ts, api/src/services/auth.service.ts, api/test/unit/passports/single-use-code.strategy.spec.ts, api/test/unit/services/auth.service.spec.ts, api/yarn.lock, shared-helpers/src/auth/AuthContext.ts, shared-helpers/src/types/backend-swagger.ts, shared-helpers/src/views/sign-in/FormSignInDefault.tsx, shared-helpers/src/views/sign-in/FormSignInPwdless.tsx, sites/partners/.env.template, sites/partners/next.config.js, sites/partners/package.json, sites/partners/src/lib/users/signInHelpers.ts, sites/partners/src/pages/_app.tsx, sites/partners/src/pages/sign-in.tsx, sites/public/src/pages/_app.tsx, sites/public/src/pages/sign-in.tsx, sites/public/src/pages/verify.tsx
We will first enable recaptcha but not have it block login, so that we can gather baseline score data from the logs
=> feat: login with v3 recaptcha (#4091)

shared-helpers/src/locales/general.json, sites/public/__tests__/components/listing/listing_sections/Neighborhood.test.tsx, sites/public/src/components/listing/ListingViewSeeds.module.scss, sites/public/src/components/listing/ListingViewSeeds.tsx, sites/public/src/components/listing/ListingViewSeedsHelpers.tsx, sites/public/src/components/listing/listing_sections/AdditionalFees.tsx, sites/public/src/components/listing/listing_sections/Features.tsx, sites/public/src/components/listing/listing_sections/Neighborhood.tsx
Releases the following commit from core: https://github.com/bloom-housing/bloom/pull/4806
=> release: public neighborhood amenities (#4806)

shared-helpers/package.json, sites/partners/package.json, sites/public/package.json, sites/public/src/pages/_app.tsx, sites/public/styles/overrides.scss, yarn.lock
Releases the following commit from core: https://github.com/bloom-housing/bloom/pull/4819
=> release: local theming (#4819)

sites/partners/package.json, sites/partners/src/pages/_app.tsx, sites/public/package.json, sites/public/src/pages/_app.tsx, yarn.lock
Releases the following commit from core: https://github.com/bloom-housing/bloom/pull/4723
=> release: upgrade axe-core/react (#4723)

api/package.json, api/yarn.lock, shared-helpers/package.json, sites/public/package.json, yarn.lock
Releases the following commit from core: https://github.com/bloom-housing/bloom/pull/4722
=> release: upgrade ts-loader (#4722)

.circleci/config.yml, sites/public/cypress.config.ts, sites/public/cypress/mockData/applicationData.ts, sites/public/cypress/support/commands.js, sites/public/src/components/browse/ListingCard.tsx, sites/public/src/patterns/SiteHeader.tsx
This PR addresses #(insert-number-here)
* Set up the public sites cypress testing suite to use the seeds designs
* Add new IDs in seeds design for Cypress testing
* Update existing Cypress custom commands 
View the cypress logs under this PR
s
=> test: seeds designs cypress test suite (#4850)

api/.env.template, api/package.json, api/src/controllers/application.controller.ts, api/src/controllers/lottery.controller.ts, api/src/services/application-exporter.service.ts, api/src/utilities/s3-helpers.ts, api/src/utilities/zip-export.ts, api/yarn.lock, shared-helpers/src/types/backend-swagger.ts, sites/partners/next.config.js, sites/partners/src/lib/hooks.ts, sites/partners/src/pages/listings/[id]/applications/index.tsx, sites/partners/src/pages/listings/[id]/lottery.tsx, yarn.lock
This PR addresses https://github.com/bloom-housing/bloom/issues/4813
This brings over the secure download functionality for the application and lottery exports 
Set your env variables properly for both backend and partners
attempt to download an application export and a lottery export you should get both from the secure s3 bucket
=> feat: hba secure download

shared-helpers/package.json, sites/partners/package.json, sites/public/package.json, sites/public/src/pages/account/application/[id]/index.tsx, yarn.lock
=> fix: reduce fetch on individual application (#4852)

api/prisma/seed-staging.ts, shared-helpers/src/locales/general.json, sites/public/__tests__/components/listing/listing_sections/Availability.test.tsx, sites/public/__tests__/components/listing/listing_sections/GetAvailabilitySubheading.test.tsx, sites/public/src/components/listing/ListingViewSeeds.module.scss, sites/public/src/components/listing/listing_sections/Apply.tsx, sites/public/src/components/listing/listing_sections/Availability.module.scss, sites/public/src/components/listing/listing_sections/Availability.tsx, sites/public/src/components/listing/listing_sections/DateSection.tsx, sites/public/src/components/listing/listing_sections/InfoCard.tsx, sites/public/src/components/listing/listing_sections/LeasingAgent.tsx, sites/public/src/components/listing/listing_sections/LotteryResults.tsx
release of https://github.com/bloom-housing/bloom/pull/4915
=> feat: public additional waitlist section (#4915)

sites/public/src/pages/_app.tsx
Releases the below commit from core. Turns Lakeview themeing on regardless of the deployment environment, so should have no visible changes.
=> refactor: apply jurisdictional theme class in prod (#5001)

README.md
Releases the below commit from core, just simple README updates
=> docs: update readme (#4538)

shared-helpers/src/views/components/BloomCard.module.scss, shared-helpers/src/views/components/BloomCard.tsx, sites/public/src/components/account/ApplicationsView.tsx, sites/public/src/components/account/FavoritesView.tsx, sites/public/src/pages/account/edit.tsx
This contains the core PR:
* bloom-housing/bloom#4849
=> release: use Seeds loading state and improve design of no favorites (#4849)

shared-helpers/__tests__/unitTypes.test.ts, shared-helpers/src/utilities/unitTypes.ts, sites/partners/__tests__/components/applications/sections/FormHouseholdDetails.test.tsx, sites/partners/src/components/applications/PaperApplicationForm/sections/FormHouseholdDetails.tsx, sites/public/__tests__/pages/account/application/[id]/index.test.tsx, sites/public/src/components/applications/SubmittedApplicationView.tsx, sites/public/src/components/shared/FormSummaryDetails.tsx, sites/public/src/lib/applications/ApplicationConductor.ts, sites/public/src/lib/applications/PreferredUnitSizeStep.ts, sites/public/src/lib/helpers.tsx, sites/public/src/pages/applications/review/summary.tsx, sites/public/src/pages/applications/start/autofill.tsx
Release of https://github.com/bloom-housing/bloom/pull/5037
=> fix: update unit groups displayed if needed (#5037)

sites/public/cypress/support/commands.js, sites/public/src/patterns/SiteHeader.tsx
This PR addresses [5045](https://github.com/bloom-housing/bloom/issues/5045)
This PR addresses issue #5045 
Update `data-testid` selector to prevent testid from changing with UI changes unrelated to the feature under test with the goal to reduce test flakiness. 
**Before** `data-testid` would change based on number of elements in navbar
**After** `data-testid` no longer uses index and will not change based on number of elements in navbar
**NOTE** - This PR only addresses the components setting the `data-testid` within bloom core. Any component where the `data-testid` is set on a component imported from ui-components will need to be a separate PR. This limits the scope of this PR to just the Public site and corresponding cypress tests.
- All automated tests continue to pass
- Manually test …
=> test: remove index from data-testid on public site (#5043)

sites/public/src/components/shared/CustomSiteFooter.module.scss
=> fix: site footer rtl (#5010)

api/package.json, api/yarn.lock, sites/partners/package.json, sites/public/package.json, yarn.lock
=> chore: upgrade webpack (#4718)

api/src/services/translation.service.ts, api/test/unit/services/translation.service.spec.ts
Release of https://github.com/bloom-housing/bloom/pull/5061
=> fix: add translations for neighborhood amenities (#5061)

api/prisma/seed-staging.ts, api/src/enums/feature-flags/feature-flags-enum.ts, shared-helpers/__tests__/testHelpers.ts, shared-helpers/src/types/backend-swagger.ts, sites/public/__tests__/components/listing/ListingViewSeeds.test.tsx, sites/public/src/components/listing/ListingViewSeeds.tsx
This features the Core PR:
* bloom-housing/bloom#5027
=> release: add listing updated at to detail page, based on feature flag

sites/public/src/components/browse/FilterDrawerHelpers.tsx, sites/public/src/components/finder/FinderRentQuestion.tsx, sites/public/src/components/finder/RentalsFinder.tsx
Release of https://github.com/bloom-housing/bloom/pull/5085
=> fix: add rent validation for finder (#5085)
