housingbayarea/bloom

apps/public-ala/.env.template, apps/public-sj/.env.template, apps/public-smc/.env.template
fixes both the listings JSONPath query strings to match what's in use and also the HOUSING_COUNSELOR_SERVICE_URLs
=> Update env templates with current urls

services/listings/listings/100_grand.json, services/listings/listings/bridgepointe.json
This should cover the two QA items that don't require https://github.com/bloom-housing/bloom/issues/380.
- add back a due date for 100 Grand since they no longer want it to be FCFS
- split up the Bridgepointe preferences
Still potentially todo (though a nice-to-have) is making sure requiredDocuments supports Markdown and then formatting that field appropriately for the bulleted list.
=> Re-enable 100Grand + Bridgepointe with minor QA fixes.

services/listings/listings/reilly_station.json
Per request. I felt bad for what looked like a copy/paste error I introduced, but the incorrect language is actually copied verbatim from the spreadsheet.
Note the second sentence they wanted to add is already right below the box, so I elected not to duplicate it.
=> Fix preference language for Reilly Station

services/listings/listings/bridgepointe.json
Fixes #106.
Hopefully Eastlake final QA will be done shortly, and then we can roll both listings to production together.
=> Set Bridgepointe to use 2020 AMI chart instead of 2019

services/listings/listings/eastlake-never-launched.json
It sounds like the Eastlake team was able to lease up their building faster than they were able to approve the listing so it's not going to launch on Bloom. We'll keep it around in a permanently disabled state in case they have another need in the future.
=> disable Eastlake listing

services/listings/listings/jones.json
You just need to have a waitlist of some size set to show the desired language, so I did that. The logic is worth re-evaluating before we expose it in partners, for which we'll want it to be more intuitive to edit, but this should be fine for now.
Fixes #123
=> set fake waitlist size to address #123

apps/public-ala/pages/applications/financial/income.tsx
For the pilot, disable income validation during the application process (Alameda site).
=> Disable income validation for the ala site

services/listings/listings/atlas.json
Fixes #133.
Note the email address was already there for the email link, so the drop-off language is just hidden.
=> Atlas maybe-final QA wording adjustments

apps/public-ala/pages/applications/start/choose-language.tsx, services/listings/listings/jones.json
Temporary comment-out of the language choice for the Jones application pilot, to be returned once translations have been done and validated.
Also hard-codes (ish) the application ID link for Jones. This will be replaced in the short-term with a hard-coded UUID directly in the database until the proper ApplicationMethods code lands upstream and is incorporated.
=> Comment out language choice from Application

backend/core/ami_charts/AlamedaCountyLIHTC2020.json, backend/core/ami_charts/AlamedaCountyTCAC2019.json, backend/core/ami_charts/OaklandFremontHUD2020.json, backend/core/ami_charts/SanMateoCountyTCAC2019.json, backend/core/ami_charts/SanMateoCountyTCAC2020.json, backend/core/ami_charts/SanMateoHUD2020.json, backend/core/src/lib/ami_charts.ts
This just copies the remainder of existing AMI tables from services/listings to backend/core
=> migrate rest of AMI charts from legacy service to backend/core

backend/core/listing_data/monarch.json
Since we'll be applying the migration that changes the type of preference ordinals to numeric before we import the monarch data, we need to change the preferences here into the new format.
Once we land all of this in production, we should go back and update all the rest of the listing JSONs as well to support future re-imports, but we can do that in a separate PR.
=> change monarch pref ordinals to numeric format

backend/core/listing_data/skylyne.json
Fixes #162.
Notes: 
- I'm actually going to apply this on staging and production via a direct SQL query hotfix so IDs stay the same, but updating the JSON here for tracking, QA, and future imports.
- I updated the ordinals here so imports work
- NB that the time zone for the Bay Area as of 1 Nov 20 is back to GMT-8, so we'll need to keep that in mind for listings through the winter.
=> extend Skylyne deadline to 1 Nov per request

backend/core/listing_data/logan.json
It was just slightly off from the real building location.
=> adjust Logan lat/lng for map display

sites/public/page_content/locale_overrides/es.json, sites/public/page_content/locale_overrides/vi.json, sites/public/page_content/locale_overrides/zh.json
[#2255](https://github.com/bloom-housing/bloom/issues/2255)
Two application string updates in other languages:
* Do you work in the City of San Jose?
* How did you hear --> Jurisdictional website (there is a core PR for a bug here, on language change you will need to refresh the page to see the translated strings)
=> chore: region and website strings

backend/core/src/migration/1650486375189-alameda-programs-and-preferences.ts, sites/partners/page_content/locale_overrides/general.json, sites/public/page_content/locale_overrides/general.json, ui-components/src/locales/general.json
[#Issue](https://github.com/bloom-housing/bloom/issues/2623)
This creates a new program and preference
Note: I think at the time of running the migrations the jurisdictions haven't been seeded, with an already stood up db this should add it 
```
INSERT INTO programs(title, subtitle, description, form_metadata)
SELECT 
'State of California - Veterans Housing and Homelessness Prevention Program (VHHP)' as title,
'' as subtitle,
'Does anyone in your household meet the following eligibility requirements? (check all that apply)' as description,
'{"key":"VHHP","type":"checkbox","options":[{"key":"veteran","extraData":[],"description":true},{"key":"veteranStatus","extraData":[],"description":true}]}' as form_metadata
;
INSERT INTO preferences(title, subtitle, description, form_metadata)
SELECT …
```
=> feat: adding new program and preferences

sites/public/page_content/AdditionalResourcesSidebar.md, sites/public/sentry.server.config.js
Description: Update content on the 'Additional Housing Opportunities and Resources' page on the San Jose public site to match #408 
Testing: This can be testing by going to the San Jose public site and ensuring that the contact info on the right side matches the following text: "For general program inquiries, you may call the Housing Department at 408-535-3860 or email [sjhousingportal@sanjoseca.gov](mailto:sjhousingportal@sanjoseca.gov)"
Question: Do I incorporate this into translations as well in this PR?
=> fix: updated resource content

sites/public/page_content/AdditionalResources.md, sites/public/page_content/AdditionalResourcesSidebar.md
This PR addresses the content updates and Spanish translations described in #403.
This can be tested by navigating to the additional resource page on the Alameda public site.
Assumptions Made/Questions:
1) In the figma, "211" was shown as linked in the description so I kept the same number linked under the "211 Alameda County Resource Finder."
2)With the addition of the new section, "Building Futures - West (Alameda)", I removed Alameda from the pre-existing Building Futures - West (San Leandro and Alameda). This was shown in the Figma but not anyway else so just wanted to verify it should be removed.
3)Is there a reason that the "Immediate Housing Assistance" and "Contact" isn't translated?
=> fix: resource and translation updates

backend/core/scripts/ami-chart-import-script.sh, backend/core/src/migration/1654636407033-alameda-2022-amicharts.ts, backend/core/src/seeder/seeds/ami-charts/alameda-hud-2022.ts, backend/core/src/seeder/seeds/ami-charts/alameda-tcac-2022.ts
This resolves: https://github.com/housingbayarea/bloom/issues/427
in order to test:
head to the partner site https://hba-partners-dev.netlify.app/
go to create/edit a listing
add a unit
notice that the new ami charts are present, and the values match up with the expected values from the spreadsheets in the ticketo
verify that the listing can save properly
verify the listing detail page displays the correct ami info 
head to the public site https://hba-public-dev.netlify.app/
verify the public preview displays the correct info as well
=> feat: creating new ami charts & script

sites/public/layouts/application.tsx
This PR addresses #454 by changing the email address linked to the contact button in the footer to [doorway@smchousing.org](mailto:doorway@smchousing.org), per our SMC stakeholders.
Steps to Review:
1. Go to SMC homepage
2. Click contact button and ensure it opens up with the correct address.
=> fix: updated email address

backend/core/src/migration/1661352526487-sanJoseAmi.ts, backend/core/src/seeder/seeds/ami-charts/san-jose-hcd-income-limits-2022.ts, backend/core/src/seeder/seeds/ami-charts/san-jose-hud-home-2022.ts
This adds new AMI charts from #446 . You can test this by reseeding locally and seeing that the migration file inserts the new chars.
=> feat: adds new san jose ami charts

sites/partners/lib/hooks.ts, sites/partners/page_content/locale_overrides/general.json, sites/partners/pages/listings/[id]/flags/index.tsx, ui-components/src/page_components/NavigationHeader.tsx
There is a bug in production where if a user opens up the `One Hundred Grand` property on the partners site the backend runs out of memory. This causes the backend to crash. The culprit is the `applicationFlaggedSets` endpoint. And although the flags tab is currently disabled, the API call is still being done on the other two tabs to get the flagged count.
This PR removes all calls to the applicationFlaggedSets and also adds a warning banner that it is under construction when the environment variable `SHOW_DUPLICATES` is equal to false.
Two options for testing (both require setting the partners .env variable of `SHOW_DUPLICATES` to FALSE:
1. Open up any closed listing and the applicationFlaggedSets call should not be happening. Should also see under construction banner instead of table on …
=> fix: disable applicationFlaggedSets call and add banner

backend/core/src/email/email.service.spec.ts, backend/core/src/email/email.service.ts
There is currently a bug in production where the confirmation email for lottery properties are showing the application due date instead of the lottery start date.
This fixes the issue by just removing the sentence where the date is listed in the email. It is a temporary fix until the new "What to expect" changes go out.
Email with date:
Email without date:
=> fix: remove lottery date from confirmation email

sites/public/page_content/resources/fremontFamily.md
The link to the Fremont family resources is a 404 page. This is the updated url
=> fix: update fremont family resources link

backend/core/src/migration/1666583981588-multiselectTranslationFix.ts
This PR addresses [#issue](https://github.com/bloom-housing/bloom/issues/3138)
This migration will update all the data for existing applications that were affected by the multiselect question translation bug
After running the migration locally. Try this also with a copy of prod db. 
Once its run, you can run the following:
```
/*
SELECT
a.id,
a.language,
a.programs,
a.preferences
FROM applications a
WHERE (a.programs != '[]' OR a.preferences != '[]')
AND a.language != 'en'
AND a.created_at > '06/01/2022'
ORDER BY created_at desc
*/
const res = []; // convert the query results to json and slap in this spot
for (const data of res) {
if (data.programs && data.programs.length) {
for (const program of data.programs) {
if (!program.key) {
console.log(`${data.id} is missing a top level key`);
} …
```
=> fix: migration to fix multiselect translation bug

backend/core/package.json, backend/core/src/listings/listings.service.ts, yarn.lock
This is a temporary fix to allow the closing of listings. The application flagged set calculation logic is triggered when a listing is manually closed. However, because that functionality is not working due to an unknown redis issue a response is never returned. This causes the save to fail. 
So for now, the fastest way to solve this issue is to comment out the code while we come up with the long term solution
=> fix: remove the queue for afs processing on listing close

backend/core/src/applications/services/applications.service.ts, backend/core/test/applications/applications.e2e-spec.ts
This adds the listing id to the error message when a user applies to a listing that is not open. This is due to the increase in instances of this happening so we can better identify the cause
=> fix: add listing id to bad request

sites/partners/src/components/applications/PaperApplicationDetails/sections/DetailsHouseholdIncome.tsx, sites/partners/src/components/applications/PaperApplicationForm/sections/FormHouseholdIncome.tsx, sites/public/src/pages/applications/financial/income.tsx
[Support issue Slack thread
](https://exygy.slack.com/archives/C02G1S19QA2/p1686000532485949)
This is a temporary fix that we hope will allow folks to continue past the income step. It removes all validation on the field, but does still require it.
Try to submit an application with non-numeric characters + numbers that are well above and below the listing's limits.
In partners it should display as that string.
- Either …
=> fix: comment out income validation and change to text field

sites/partners/src/lib/applications/formatApplicationData.ts
This PR addresses #3513
No matter what you select on the "Time Submitted" field on the paper application for AM/PM it always selects AM on submission. This is due to a mismatch in the mapping of formatting when converting it to a 24 hour string. A capital "A" is for AM/PM whereas a lower case "a" is for am/pm. We need it to be lowercase because that is what we get back from the timeField.
Go to a listing and create a manual application submission in partners. Select "PM" when selecting the "Time Submitted". On save it should now display pm on this page along with the applications table. 
You should be able to also edit the application and it should properly save the new time.
- Review the code …
=> fix: get correct time period for submitted

sites/public/next.config.js, sites/public/src/page_content/jurisdiction_overrides/alameda/jurisdiction-footer-section.tsx, sites/public/src/page_content/jurisdiction_overrides/alameda/locale_overrides/es.json, sites/public/src/page_content/jurisdiction_overrides/alameda/locale_overrides/general.json, sites/public/src/page_content/jurisdiction_overrides/alameda/locale_overrides/tl.json, sites/public/src/page_content/jurisdiction_overrides/alameda/locale_overrides/vi.json, sites/public/src/page_content/jurisdiction_overrides/alameda/locale_overrides/zh.json, sites/public/src/page_content/jurisdiction_overrides/san_jose/jurisdiction-footer-section.tsx, sites/public/src/page_content/jurisdiction_overrides/san_jose/locale_overrides/es.json, sites/public/src/page_content/jurisdiction_overrides/san_jose/locale_overrides/general.json, sites/public/src/page_content/jurisdiction_overrides/san_jose/locale_overrides/vi.json, sites/public/src/page_content/jurisdiction_overrides/san_jose/locale_overrides/zh.json, sites/public/src/page_content/jurisdiction_overrides/san_mateo/jurisdiction-footer-section.tsx, sites/public/src/page_content/jurisdiction_overrides/san_mateo/locale_overrides/es.json, sites/public/src/page_content/jurisdiction_overrides/san_mateo/locale_overrides/general.json, sites/public/src/page_content/jurisdiction_overrides/san_mateo/locale_overrides/vi.json, sites/public/src/page_content/jurisdiction_overrides/san_mateo/locale_overrides/zh.json
This PR addresses #618
Adds link in footer to doorway. Used approach with doorway link from #621 (so here is required locally `DOORWAY_URL=https://dev.doorway.housingbayarea.org` env variable)
For Alameda / San Jose and San Mateo check footer if it starts with doorway link. Test every language (Filipino only available in Alameda)
- Either explicitly ask a clarifying question, request changes, or approve the PR if there are small …
=> feat: add doorway link to footer

backend/core/src/application-flagged-sets/application-flagged-sets-cronjob.service.ts
This PR addresses #3517
There is an issue where on at least 7 listings in production there is a application flagged set group that has an unusually high number of "pending review". Some of them in the thousands. This is due to a change that went in last week, the upgrade of TypeORM. Although the logic is the same, under the covers it appears that a different behavior is happening when calculating if there is a conflicting Email. Specifically if there is an application that does not have an email (email is null and `no_email` is true) it will conflict with all other applications that also don't have an email listed.
This is the first step of two to address the issue. When running the afs cron job this PR updates the calculation on email conflict by only running it if the applicant has an …
=> fix: add check in afs for null email

backend/core/src/auth/services/user.service.ts, shared-helpers/src/locales/es.json, shared-helpers/src/locales/general.json, shared-helpers/src/locales/tl.json, shared-helpers/src/locales/vi.json, shared-helpers/src/locales/zh.json
This is a patch to release:
Some missing translations (https://github.com/bloom-housing/bloom/issues/3544)
Adding some additional logging to help track down an user confirm() error (https://github.com/bloom-housing/bloom/issues/3537)
Testing: 
the logging error isn't something we've been able to replicate so looking to see in the deployed state to help track down how this is happening. No testing on our end needed
missing translations: 
```
create a public user (or use an existing user)
go through the reset password work flow
enter a password that would be too weak abcdef for example, you should now get a translated error message
```
=> fix: 07-14-2023 hot fixes

backend/core/src/listings/listings.module.ts, backend/core/src/listings/listings.service.ts, backend/core/src/listings/tests/listings.service.spec.ts, backend/core/test/listings/listings.e2e-spec.ts
This is a change that was requested by the Doorway team that was not able to be completed before the launch. The listing detail page in Doorway that pull from HBA shows the county name under the listing name. The quick fix before launch was to manually add the county names to all of the listings. However, any new listing or updated listing that county field won't be there so it just says "county" on the page.
Correctly shown here: https://housingbayarea.mtc.ca.gov/listing/ext/ab2de5f2-c569-41f2-96e3-daca29f70248
Incorrectly shown here: https://housingbayarea.mtc.ca.gov/listing/ext/6f17951f-b61d-4d23-be38-52f13ad28c1e
In order to get this to work a call to the jurisdiction service is first done to get the jurisdiction name which I then use to map to the correct county.
This is only needed …
=> fix: add county to all create/update listing

sites/public/src/pages/applications/financial/income.tsx
This PR addresses [#3675](https://github.com/bloom-housing/bloom/issues/3675)
We disabled the income validation on the application flow for HBA back in June with this commit: https://github.com/housingbayarea/bloom/pull/620. However, it was accidentally reverted with the next sync of Core. This adds it back as discussed [here](https://exygy.slack.com/archives/C02G1S19QA2/p1697056352601459) 
This can be tested by doing an application on a listing that has a minimum income. You should be able to apply to the listing with an inputted income lower than the minimum income. …
=> fix: disable income validation

backend/core/src/email/email.service.spec.ts, backend/core/src/email/email.service.ts, backend/core/src/listings/listings.service.ts, backend/core/test/listings/listings.e2e-spec.ts
Chery pick for: https://github.com/bloom-housing/bloom/issues/3699 
original pr: https://github.com/bloom-housing/bloom/pull/3700
=> fix: listingName, approval email from listingJuris (#3700)

sites/public/__tests__/components/listing/GetApplication.test.tsx, sites/public/src/components/listing/GetApplication.tsx, sites/public/src/components/listing/ListingView.tsx, sites/public/src/pages/applications/review/summary.tsx, sites/public/src/pages/applications/start/choose-language.tsx, sites/public/src/pages/preview/listings/[id].tsx
This PR addresses #3780 but now in HBA!
This PR updates the application redirect to address the case where user's applied to a draft listing. There is also some custom handling included to preserve the preview listing functionality for partner's users. While we had a preview prop on the ListingView component to disable the apply online button, that prop has not been used for at least 18 months. This means that partners have been able to look through their application in the preview stage for a while now. Considering this and talking with Sarah, I included changes to preserve this partner's ability while still blocking them or a malicious user from submitting an application.
This can be tested locally by finding the id of a draft listing, finding its public detail page via url, and seeing …
=> fix: updated application checks

shared-helpers/__tests__/views/multiselectQuestions.test.ts, shared-helpers/src/views/multiselectQuestions.tsx, sites/partners/src/components/applications/PaperApplicationForm/sections/FormMultiselectQuestions.tsx, sites/public/src/components/shared/FormSummaryDetails.tsx, sites/public/src/lib/helpers.tsx
This PR addresses:
https://github.com/bloom-housing/bloom/issues/3856
https://github.com/bloom-housing/bloom/issues/3857
Support Slack thread: https://exygy.slack.com/archives/C02G1S19QA2/p1707140129651329
Some applications with a specific preference were coming through as non-English, and sometimes they had periods at the end / other times they did not.
Create a new preference with the following options:
* `I'm an option, and I have a comma, period, and apostrophe.`
* `I'm a custom opt out option, and I also have all three.`
The comma, period, and apostrophe are "characters" that react-hook-form removes from object keys. The issue was failing comparisons between the two versions of these strings, so everywhere we are comparing options, I'm stripping the characters. We honestly need a …
=> fix: foreign language in export

backend/core/src/migration/1707508859920-multiselectTranslationFix.ts
This PR addresses #3856
Multiselect questions that have a comma, period, or apostrophe were not getting properly untranslated back to english in order to get sent back to the backend. The fix for that has already been released, but this is a migration script to update all of the existing data that was incorrectly saved.
It only impacted one property and for applications that submitted in non-english so this script targets just those applications
In order to test this you'll need to have a copy of the production database since it is reliant on the listing id and the specific preferences that are on that listing
- [] I have made corresponding changes to the documentation
- Review the code itself …
=> fix: untranslate non-english preferences in db

backend/core/src/migration/1707941488208-multiselectTranslationFix2.ts
This PR addresses #3856
For the listing that had the mistranslated preferences due to the commas there were six applications that were of language "en" but had preferences saved in a different language. This was not taken into account for the first script so this is a second one to explicitly untranslate those six applications
In order to test this you'll need to have a copy of the production database since it is reliant on the listing id and the specific preferences that are on that listing. Once setting that on your local DB you should be able to run `yarn db:migration:run` in backend/core
- Pull the changes down locally and test that the …
=> fix: second script to cleanup last applications

api/src/services/listing.service.ts
This PR addresses #[495](https://github.com/metrotranscom/doorway/issues/495)
Doorway relies on our site for data from the HBA sites. And as part of that it also links back to HBA for the application flow. With the latest Prisma change we slimmed down the jurisdiction data returned on listings and the url link for the jurisdiction is no longer returned
To solve this on the external endpoint we need to add the `publicUrl` field to the jurisdiction on the new /external endpoint
- Pull …
=> fix: add all of the jurisdiction data to external

api/src/controllers/application.controller.ts, api/src/services/application.service.ts, api/test/integration/application.e2e-spec.ts, api/test/integration/permission-tests/permission-as-no-user.e2e-spec.ts, api/test/unit/services/application.service.spec.ts
The prisma change over accidentally removed some permissioning around application get endpoints. This is the first one to resolve the immediate issue of the endpoint being open to everyone. Will follow-up with more targeted permissioning around logged in users as well
- Also review the acceptance criteria on the Netlify deploy preview (noting that these do not yet include any backend …
=> fix: add security around application list

api/src/services/application-flagged-set.service.ts, api/src/services/application.service.ts, api/test/unit/services/application-flagged-set.service.spec.ts
fixes a problem where on the partner site we weren't selecting listing id when getting applications, so we were getting errors
log in as juris admin, try to get a listing -> application tab you should now be able to
=> fix: Application perm hotfix

sites/partners/src/components/listings/ListingFormActions.tsx
This PR addresses #3996
This fix resolves the error below which was blocking users from clicking the "Approve and Publish" button from the detail (not edit) view. This is caused by a type mismatch. The frontend listing data had the ListingMultiSelectQuestionType shape but the update function in the listing.service was expecting an idDto for listing multiselect question data. After talking with @YazeedLoonat, it was decided to do the work on the frontend to format the data since other formatting work is already done there instead of on the backend. 
**Note**: Since the technical notes in the attached ticket present a more thorough investigation around consistent submitting of listing updates, I decided this one off fix was okay for now.
This can be tested locally by opening a partners user …
=> fix: account for multiselect type mismatch

api/prisma/migrations/10_update_rule_keys_to_lowercase/migration.sql, api/src/controllers/app.controller.ts, api/src/enums/user/view-enum.ts, api/src/services/app.service.ts, api/src/services/application-csv-export.service.ts, api/src/services/application-flagged-set.service.ts, api/src/services/auth.service.ts, api/src/services/user.service.ts, api/test/integration/application-flagged-set.e2e-spec.ts, api/test/integration/permission-tests/permission-as-juris-admin-correct-juris.e2e-spec.ts, api/test/unit/services/application-csv-export.service.spec.ts, api/test/unit/services/application-flagged-set.service.spec.ts, api/test/unit/services/application.service.spec.ts, api/test/unit/services/user.service.spec.ts, shared-helpers/src/types/backend-swagger.ts, sites/partners/cypress.config.ts, sites/public/cypress.config.ts
feat: a cuppa https://github.com/bloom-housing/bloom/pull/3994
fix: cuts time to get an app export https://github.com/bloom-housing/bloom/pull/3978
perf: run all cypress specs https://github.com/bloom-housing/bloom/pull/3979
fix: case insensitive name matching for applicants https://github.com/bloom-housing/bloom/pull/4021
fix: account for multiselect type mismatch https://github.com/bloom-housing/bloom/pull/4025
=> HBA Release 04 18 2024

api/src/controllers/listing.controller.ts, api/test/integration/api-key-guard.e2e-spec.ts
Listing reads no longer behind api pass key
=> fix: reading a listing shouldn't be protected

sites/public/src/components/listing/ListingView.tsx
This PR addresses #4135
This PR updates the logic to show the submit application section to account for the mailing and dropoff addresses to be undefined but the address type is same as leasing agent.
Create a listing with "Are postmarks considered?" marked as Yes, a paper app attached, indicate a received by date & time, and with both the mailing address and the drop-off address marked as same as the leasingAgentAddress... the submit application section should show on the public side with the corresponding postmark information.
- Either (1) explicitly ask a clarifying question, (2) request …
=> fix: include check for address type (#4136)

sites/public/src/pages/preview/listings/[id].tsx
PULLED FROM CORE: 
This PR addresses #4147 
This PR adds in language to the headers of the listings call on the preview page so that it matches the [slug.tsx] headers. This way the translation service is called within the listingService.findOne() call.
This can be tested by pulling this down locally, previewing a listing from the partner's side and see that most if not all strings are translating with the exception of a few particular fields such as "or one month's rent may be higher for lower credit scores" which are known by Sarah. If you wish you can uncomment the new line to see the difference.
- Pull the changes down locally and test that the acceptance criteria …
=> fix: add language to headers (#4148)

api/.env.template, api/src/services/user.service.ts, api/test/integration/user.e2e-spec.ts, api/test/unit/services/user.service.spec.ts
This PR addresses #4089. 
This PR now incorporates some points that @mcgarrye came up in discussing the previous https://github.com/bloom-housing/bloom/pull/4090 addressing this issue. Specifically in HBA, an alameda public user is able to log in to the san jose site and see applications from alameda in the san jose portal. Matching fully on the public url from the users jurisdiction would mean the forgot password experience is incorporating security that users aren't experiencing on the sign in page itself leading to a confusing experience. This issue is captured here https://github.com/bloom-housing/bloom/issues/4119
As a result of this, this PR just checks that a public user is not using the partners portal. Additionally, this PR updates the env and env template to just include …
=> fix: partner and public matching (#4090)

api/src/services/script-runner.service.ts
This PR addresses #4094 
This PR updates the ami import script runner service to include more detailed instructions on how to pre-process ami data from Google Sheets. 
Read the comments and look through the notion page based on the commenting instructions
=> fix: ami import formatting instructions (#4163)

api/prisma/migrations/14_add_lottery_status_enums/migration.sql, api/prisma/schema.prisma, api/prisma/seed-helpers/listing-factory.ts, api/src/controllers/listing.controller.ts, api/src/dtos/listings/listing-lottery-status.dto.ts, api/src/dtos/listings/listing.dto.ts, api/src/services/listing.service.ts, api/test/integration/listing.e2e-spec.ts, api/test/unit/services/listing.service.spec.ts, shared-helpers/src/types/backend-swagger.ts
This PR addresses [#(4057)](https://app.zenhub.com/workspaces/bloom-5dc32d7144bd400001315dac/issues/gh/bloom-housing/bloom/4057)
Releasing from core: https://github.com/bloom-housing/bloom/pull/4167
Run migration and run backend in the terminal. Use the swagger open api for the following flows.
Flow 1: Login as an admin, attempt to change the status of a active listing to releasedToPartners, you should receive an error since listing is not closed.
Flow 2: Login as an admin, attempt to change the status of a closed listing to releasedToPartners, you should receive an error since it must be in approved.
Flow 3: Change the status manually in the db to approved, login as an admin, attempt to change the status of a closed listing to releasedToPartners, confirm change was successful, attempt to …
=> feat: lottery status (released to partners / retracted) (#4167)

api/prisma/seed-staging.ts, sites/partners/src/components/listings/PaperListingForm/UnitForm.tsx
This PR addresses [#4174](https://github.com/bloom-housing/bloom/issues/4174)
Pulls the following commit from core
* 3095b004a - fix: filter ami charts by jurisdition (#4177)
=> fix: filter ami charts by jurisdition (#4177)

api/prisma/seed-helpers/listing-factory.ts, api/src/services/application.service.ts, api/test/integration/application.e2e-spec.ts, api/test/integration/permission-tests/permission-as-admin.e2e-spec.ts, api/test/integration/permission-tests/permission-as-juris-admin-correct-juris.e2e-spec.ts, api/test/integration/permission-tests/permission-as-juris-admin-wrong-juris.e2e-spec.ts, api/test/integration/permission-tests/permission-as-no-user.e2e-spec.ts, api/test/integration/permission-tests/permission-as-partner-correct-listing.e2e-spec.ts, api/test/integration/permission-tests/permission-as-partner-wrong-listing.e2e-spec.ts, api/test/integration/permission-tests/permission-as-public.e2e-spec.ts, api/test/unit/services/application.service.spec.ts, sites/public/src/pages/applications/review/summary.tsx, sites/public/src/pages/applications/start/choose-language.tsx
This PR addresses https://github.com/metrotranscom/doorway/issues/698
This PR updates the logic on the FE and BE to block application submissions from past due applications and listings that do not have the common application.
Note that these changes collides with a few existing bugs:
1) You'll notice the addToast line is commented out. I discovered a bug while testing this PR that results in infinite re-renders and subsequently, endless toasts. #4181 
2) If you change a listing that had a commonApp and answer no to digitalApp, the commonDigitalApp field remains true. The logic checks for both but I wrote up a ticket here: #4182 
3) application.e2e-spec.ts has significant amounts of duplicate (copy-pasta) code. Particularly in the creation of dtos. Instead, a base dto should be created …
=> fix: improve application submission logic (#4179)

shared-helpers/src/locales/es.json, shared-helpers/src/locales/general.json, shared-helpers/src/locales/tl.json, shared-helpers/src/locales/vi.json, shared-helpers/src/locales/zh.json
This PR addresses [#(4122)](https://app.zenhub.com/workspaces/bloom-5dc32d7144bd400001315dac/issues/gh/bloom-housing/bloom/4122)
Releases: https://github.com/bloom-housing/bloom/pull/4219
Using each language, change the email address in the public Account Settings page and verify the new copy appears in the alert.
=> release: change email update copy

sites/partners/__tests__/pages/listings/lottery.test.tsx, sites/partners/src/pages/listings/[id]/lottery.tsx
This PR addresses [#(4058)](https://app.zenhub.com/workspaces/bloom-5dc32d7144bd400001315dac/issues/gh/bloom-housing/bloom/4058)
Releases https://github.com/bloom-housing/bloom/pull/4239
Sign into Partners as a admin, navigate to a closed listing opted into lottery, go to lottery tab, click Run Lottery. Should match image below.
=> release: remove errant lottery copy

shared-helpers/src/locales/general.json, sites/public/src/layouts/application.tsx
This PR addresses [#(4251)](https://app.zenhub.com/workspaces/bloom-5dc32d7144bd400001315dac/issues/gh/bloom-housing/bloom/4251)
Update the banner on SMC with new copy about doorway transition.
Set San Mateo as JURISDICTION_NAME for public site. Run application and view banner. Confirm copy is correct.
=> feat: smc - update banner with doorway transition info

api/src/dtos/listings/listing-update.dto.ts, api/src/dtos/listings/listing.dto.ts, api/src/utilities/lottery-date-validator.ts, api/test/unit/utilities/lottery-date-validator.spec.ts, sites/partners/src/components/listings/PaperListingDetails/sections/DetailRankingsAndResults.tsx, sites/partners/src/components/listings/PaperListingForm/sections/RankingsAndResults.tsx
This PR addresses [#(4212)](https://app.zenhub.com/workspaces/bloom-5dc32d7144bd400001315dac/issues/gh/bloom-housing/bloom/4212)
Release https://github.com/bloom-housing/bloom/pull/4250
Create or edit a listing in the partners portal.
Save with First Come First Serve selected. No errors should appear.
Edit and save with Lottery selected and No selected for optin. No errors should appear.
Edit and select Yes for optin. Do not fill out start date, start time and end time fields. Error should appear and fields should be highlighted. Cancel edit.
Edit and select Yes for optin. Fill out some but not all of the fields. Error should appear and fields should be highlighted. Cancel edit.
Edit and select Yes for optin. Fill out all of the fields. Save and no errors should appear.
Edit and remove …
=> release: require lottery date time fields

shared-helpers/src/locales/es.json, shared-helpers/src/locales/general.json, shared-helpers/src/locales/tl.json, shared-helpers/src/locales/vi.json, shared-helpers/src/locales/zh.json, shared-helpers/src/views/address/FormAddressAlternate.tsx, shared-helpers/src/views/multiselectQuestions.tsx, sites/partners/src/components/applications/PaperApplicationForm/sections/FormMultiselectQuestions.tsx, sites/public/src/pages/account/edit.tsx, sites/public/src/pages/applications/contact/address.tsx, sites/public/src/pages/applications/contact/alternate-contact-contact.tsx, sites/public/src/pages/applications/contact/alternate-contact-name.tsx, sites/public/src/pages/applications/contact/alternate-contact-type.tsx, sites/public/src/pages/applications/contact/name.tsx, sites/public/src/pages/applications/household/member.tsx, sites/public/src/pages/create-account.tsx
This PR releases #4260 
This PR updates the length validation on Zip Code fields to be 10 which matches the verify endpoint length. This also updates the error message be take in the length rather than hardcoding 64 characters.
This can be tested by attempting to fill out the application and zip code field with more than 10 characters and seeing the appropriate error message.
=> fix: update length requirement and error messaging (#4261)

api/prisma/seed-helpers/listing-factory.ts, api/prisma/seed-staging.ts, api/src/controllers/script-runner.controller.ts, api/src/services/script-runner.service.ts, api/test/unit/services/script-runner.service.spec.ts, shared-helpers/src/types/backend-swagger.ts
This PR addresses [#(4258)](https://app.zenhub.com/workspaces/bloom-5dc32d7144bd400001315dac/issues/gh/bloom-housing/bloom/4258)
Releases: https://github.com/bloom-housing/bloom/pull/4267
Reseed local database. By default, there should be 2 lottery listings. If you check the db, they will have lotteryOptIn set to `null`. Login as an admin and go to the API UI. Call the `optOutExistingLotteries` script endpoint. You should see 2 printed in the console. Check the database to verify the correct listings have been updated.
- Either (1) explicitly ask a clarifying question, (2) request changes, or …
=> release: opt out existing lotteries

api/src/enums/applications/household-member-relationship-enum.ts, shared-helpers/src/locales/es.json, shared-helpers/src/locales/general.json, shared-helpers/src/locales/tl.json, shared-helpers/src/locales/vi.json, shared-helpers/src/locales/zh.json, shared-helpers/src/types/backend-swagger.ts
This PR addresses https://github.com/bloom-housing/bloom/issues/4266
Adds a "Live-in Aide" option for household members (note that we decided it should be "Live-in Aide" rather than "Live in Aid").
Also note Google Translate for Filipino just gave "Live-in Aide" so maybe there's not a native term for it (or it doesn't know about one).
Fill out an online application and verify you can submit Live-in Aide as an option for a household member.
- Either (1) explicitly ask a clarifying question, (2) request changes, or (3) approve the PR, even if there are very small remaining changes, if you don't …
=> feat: add Live In Aid as household member relationship

api/.env.template, api/src/controllers/listing.controller.ts, api/src/dtos/listings/listing-duplicate.dto.ts, api/src/services/listing.service.ts, api/src/services/lottery.service.ts, api/test/integration/listing.e2e-spec.ts, api/test/integration/permission-tests/permission-as-admin.e2e-spec.ts, api/test/integration/permission-tests/permission-as-juris-admin-correct-juris.e2e-spec.ts, api/test/integration/permission-tests/permission-as-juris-admin-wrong-juris.e2e-spec.ts, api/test/integration/permission-tests/permission-as-no-user.e2e-spec.ts, api/test/integration/permission-tests/permission-as-partner-correct-listing.e2e-spec.ts, api/test/integration/permission-tests/permission-as-partner-wrong-listing.e2e-spec.ts, api/test/integration/permission-tests/permission-as-public.e2e-spec.ts, api/test/unit/services/listing.service.spec.ts, api/test/unit/services/lottery.service.spec.ts, shared-helpers/src/types/backend-swagger.ts
This PR addresses [#(799)](https://app.zenhub.com/workspaces/bloom-5dc32d7144bd400001315dac/issues/gh/metrotranscom/doorway/799)
Releases:
https://github.com/bloom-housing/bloom/pull/4313
https://github.com/bloom-housing/bloom/pull/4307
https://github.com/bloom-housing/bloom/pull/4314
Run partner portal and api and login as a admin user.
Have the listing id for the listing you would like to duplicate.
Fill out the payload for listings/duplicate. Set storedListing.id to the above.
Cases:
Set name to a unique name, set includeUnits to true. Should create a new draft listing with the name given which is otherwise identical to the original listing, including the units.
Set name to a unique name, set includeUnits to false. Should create a new draft listing with the name given which is …
=> release: listing duplication endpoint

sites/partners/src/pages/listings/[id]/lottery.tsx
This PR addresses #4300 
This PR completes an outstanding todo to include the releaseDate in the partners messaging seen in the issue description. It also handles the case of releasing and retracting by finding the most recent release date.
This can be tested by creating a lottery listing as an admin and releasing that lottery. Then as a partner user see the date and time reflected in the lottery publish card. You can also test retracting and releasing the lottery to see the time updated.
- Either (1) explicitly ask a clarifying question, (2) request changes, or (3) approve the PR, even if …
=> fix: add releaseDate to partner card (#4315)(release)

api/src/services/lottery.service.ts, api/test/unit/services/lottery.service.spec.ts
This PR addresses [#(4310)](https://github.com/bloom-housing/bloom/issues/4310)
Releases [fix: history log fix](https://github.com/bloom-housing/bloom/pull/4353)
For a lottery listing, close the listing and check it it appears in the history log. Make a change and save it to the listing, a new log should not be present. Reopen the listing, close the listing again, a new log should appear. All lottery related logs should still function as expected.
- Either (1) explicitly ask a clarifying question, (2) request changes, or (3) approve the PR, even if there are very small remaining changes, if …
=> release: history log fix

sites/partners/src/components/listings/PaperListingForm/sections/SelectAndOrder.tsx
This PR addresses #4360 
This PR updates the defaultSelected Logic within the "Select Preference" drawer to match on id rather than text to handle multiple preferences with the same name.
Run locally, Log in to partners as an admin, Add preferences with the same name or make multiple copies of existing preferences, Add only some of the preferences with the same name to the listing, Save, Go back to Edit and view the preferences, and only the ones you selected will show as checked. Previously, all with the same name would show as selected.
- Either (1) explicitly ask a clarifying question, (2) …
=> fix: match pref on id (#4372)

api/prisma/seed-staging.ts, api/src/services/lottery.service.ts, api/src/utilities/application-export-helpers.ts, api/test/unit/services/lottery.service.spec.ts
Pulls in Commit from core for issue #4282
Can test using the same steps as found here: https://github.com/bloom-housing/bloom/pull/4351
=> fix: remove opt out preferences from export and lottery (#4351)

api/src/controllers/script-runner.controller.ts, api/src/modules/script-runner.module.ts, api/src/services/script-runner.service.ts, api/test/unit/services/script-runner.service.spec.ts, shared-helpers/src/types/backend-swagger.ts
This PR addresses [#(794)](https://github.com/housingbayarea/bloom/issues/794)
Script collects the existing applications to Sparks Homes and updates the preferences jsonb for each application with corrected options strings.
Pull down prob db copy from Heroku and setup locally.
Check the preferences field for applications associated with listing id 'a055ce66-a074-4f3a-b67b-6776bec9926e'
Start app, sign in as an admin through partner portal or api.
Through the api, call `/scriptRunner/correctApplicationPreferenceDataForSparksHomes`.
Check the preferences field for applications associated with listing id 'a055ce66-a074-4f3a-b67b-6776bec9926e'
and assert update worked.
query:
`SELECT preferences
FROM applications
WHERE listing_id='a055ce66-a074-4f3a-b67b-6776bec9926e';`
- Read and understand …
=> feat: correction script for sparks homes application preferences

sites/public/src/page_content/jurisdiction_overrides/alameda/jurisdiction-footer-section.tsx, sites/public/src/page_content/jurisdiction_overrides/san_jose/jurisdiction-footer-section.tsx
This PR addresses #4456
This removes the links to SMC site on both Alameda and San Jose
- Start up public site with jurisdiction set to `Alameda`
- No link to SMC should be on the footer
- Start up public site with jurisdiction set to `San Jose`
- No link to SMC should be on the footer
=> fix: remove smc references in footers

api/src/controllers/listing.controller.ts, api/src/dtos/listings/listing-csv-query-params.dto.ts, api/src/services/listing-csv-export.service.ts, shared-helpers/src/types/backend-swagger.ts
This PR addresses https://github.com/bloom-housing/bloom/issues/4470
This creates a new GenAI export endpoint that does exactly what the listing csv export does in terms of listings and units but adds an additional csv in the zip for the ami chart data 
Provide instructions so we can review, including any needed configuration, and the test cases that need to be QAd.
=> feat: [GenAI] new listing gen ai export endpoint

sites/partners/src/lib/hooks.ts, sites/partners/src/pages/users/index.tsx
This PR addresses #(insert-number-here)
When attempting to edit a user we do a call to get a list of all of the listings. This is for the displaying of the listing checkboxes. However, there are now too many listings in HBA and the response is too big for Netlify to return. This is an extra big response because we are returning way more values of the listings than what is needed. 
This PR changes the requested view from "base" to "fundamentals" so units data is not returned.
Long term we should also create a view that only has ids and names.
Editing a partner user should still work
- Either …
=> fix: reduce the view for user edit

sites/partners/src/lib/hooks.ts
this makes it so we are actually using the fundamental view from https://github.com/housingbayarea/bloom/pull/810
=> fix: using fundamental view

api/src/passports/mfa.strategy.ts, api/src/passports/single-use-code.strategy.ts, api/src/utilities/passport-validator-utilities.ts, api/test/unit/passports/passport-validator-utilities.spec.ts
RELEASE
This PR addresses #4473 
This PR changes the function isUserLockedOut to return the verified failedLoginAttempts count explicitly. Before, it was failing to reset after the lockout period was over because of an assumption that it was pass by reference rather than value.
Note that there is an existing bug in core: https://github.com/bloom-housing/bloom/issues/4284
This can be tested locally by locking out a public user via 5 failed password attempts (you'll have to verify in network tab). Then, go into the DB and set that user's last login at date to be last year. Lastly, try to log in again with an incorrect password and see that the count has been reset (via the network tab).
- Review the code itself from a …
=> fix: return updated failed login attempts (#4474)

api/src/services/listing.service.ts
This PR addresses #4490
This PR updates the duplicate function in the listing service to transform the application methods array to how the listing create function expects it. 
Test copying a listing with no paper app, paper app selected but not uploaded, one paper app, multiple paper apps... and ensure that the listing and assets are copied over without error.
=> fix: handle copying app methods (#4491)

shared-helpers/src/auth/RequireLogin.tsx, shared-helpers/src/locales/es.json, shared-helpers/src/locales/general.json, shared-helpers/src/locales/tl.json, shared-helpers/src/locales/vi.json, shared-helpers/src/locales/zh.json, shared-helpers/src/utilities/MessageContext.ts, sites/public/src/components/account/ConfirmationModal.tsx, sites/public/src/pages/applications/review/summary.tsx, sites/public/src/pages/applications/start/choose-language.tsx
This PR pulls in the following Core PRs:
- bloom-housing/bloom#4302
- bloom-housing/bloom#4466
=> release: various Toast updates

api/prisma/seed-helpers/feature-flag-factory.ts, api/src/controllers/feature-flag.controller.ts, api/src/dtos/feature-flags/feature-flag-associate.dto.ts, api/src/dtos/feature-flags/feature-flag-create.dto.ts, api/src/dtos/feature-flags/feature-flag-update.dto.ts, api/src/dtos/feature-flags/feature-flag.dto.ts, api/src/dtos/jurisdictions/jurisdiction-update.dto.ts, api/src/dtos/jurisdictions/jurisdiction.dto.ts, api/src/modules/app.module.ts, api/src/modules/feature-flag.module.ts, api/src/permission-configs/permission_policy.csv, api/src/services/feature-flag.service.ts, api/src/services/jurisdiction.service.ts, api/test/integration/feature-flag.e2e-spec.ts, api/test/integration/permission-tests/permission-as-admin.e2e-spec.ts, api/test/integration/permission-tests/permission-as-juris-admin-correct-juris.e2e-spec.ts, api/test/integration/permission-tests/permission-as-juris-admin-wrong-juris.e2e-spec.ts, api/test/integration/permission-tests/permission-as-no-user.e2e-spec.ts, api/test/integration/permission-tests/permission-as-partner-correct-listing.e2e-spec.ts, api/test/integration/permission-tests/permission-as-partner-wrong-listing.e2e-spec.ts, api/test/integration/permission-tests/permission-as-public.e2e-spec.ts, api/test/unit/services/feature-flag.service.spec.ts, api/test/unit/services/jurisdiction.service.spec.ts, shared-helpers/src/types/backend-swagger.ts
This PR addresses [#(4459)](https://github.com/bloom-housing/bloom/issues/4459)
Creates the module, controller and service files for the new Feature Flag table. Allows for standard CRUD methods, as well as a list endpoint and an endpoint to add/remove jurisdiction associations with the flag (`associateJurisdictions`). Permissions are limited to admin only. Flags associated with jurisdictions will appear when jurisdiction data is returned.
Start up the backend. Login as an admin, either through the API or partners portal. Test each endpoint:
- Create a feature flag
- Get the feature flag using the id returned ^^
- Update the feature flag using the id
- Get the feature flag to verify update
- Associate jurisdiction(s) with the flag
- Get the feature flag to verify association
- Get the …
=> release: feature flag consumption (#4489)

api/src/services/listing.service.ts, api/test/unit/services/listing.service.spec.ts
This PR addresses #773 
During Qa, it was discovered that the publishedAt date was showing as none for many open listings. This was because we were not covering the case where a user publishes a listing from scratch, never first saving it as a draft.
Create a listing from scratch and publish it without saving it as a draft. In the partner's listing table, you should see today's date.
=> fix: publishedAt on create (#4479)

api/src/services/listing.service.ts
This PR addresses [#(982)](https://github.com/metrotranscom/doorway/issues/982)
Listings with a BuildingSelectionCriteriaFile could not be duplicated due to an issue re-creating the asset. This is fixed by not passing the existing asset id to the new copy.
- Create or edit a listing to have a building selection criteria file.
- Copy the listing
- Confirm the building selection criteria file is present on the copy listing
- Publish the copy listing
- Go to the public site, view the copy listing, view the building selection criteria file
- Either (1) explicitly ask a clarifying question, (2) …
=> fix: building selection criteria adjustment (#4505)

sites/partners/src/components/settings/PreferenceDrawer.tsx
This PR releases https://github.com/metrotranscom/doorway/issues/1004
This PR updates the watch function to include a default value. The issue was that we were defaulting the canYouOptOutQuestion to true on all preferences that didn't explicitly set to no but depending on the watch value to be Yes in order to show the optOutText field. As a result, the watch value was undefined on load and wouldn't set to Yes until the user directly interacted with the radio leading to the confusing experience described in ticket. This one line change handles that case. 
This can be tested by editing existing preferences and adding new ones. In both cases, if the canYouOptOutQuestion shows yes, the optOutText field should be visible
- …
=> fix: set optOut watch default value (#4512)

sites/partners/src/components/applications/PaperApplicationDetails/sections/DetailsHouseholdMembers.tsx, sites/partners/src/components/applications/PaperApplicationForm/PaperApplicationForm.tsx, sites/partners/src/components/applications/PaperApplicationForm/sections/FormHouseholdMembers.tsx
This PR addresses [#977 ](https://github.com/metrotranscom/doorway/issues/977)
This PR updates the deleteModal open logic to handle an orderId=0. When a user applies online, the first household member is set to an OrderId of 0 but when added via the partner's side, it adds it with an orderId of 1. This PR also updates the ordering on the partner's side so that a user sees the household members in the order they added them (public side is already demonstrating this behavior). However, I stopped short of refactoring the orderId to be used more consistently to avoid any risks in conflicting with existing data. Instead, that work is captured here: https://github.com/bloom-housing/bloom/issues/4511
Note: I had originally assumed the orderId was null causing this issue but querying production …
=> fix: household member delete + order (#4510)

api/src/utilities/application-export-helpers.ts, api/test/unit/utilities/application-export-helpers.spec.ts, shared-helpers/__tests__/formKeys.test.ts, shared-helpers/src/utilities/formKeys.ts
This PR addresses https://github.com/metrotranscom/doorway/issues/1009
The ticket also mentions cleaning up the instances where doorway entered a space to get the "other" field to save which this PR doesn't cover.
This PR includes two different empty string checks in the formKeys file which prevents the selection of other without entering further information from being filtered out or being stored with a colon and space. 
This can be tested by 
a) submitting an online app with a mix of demographic data (including other selections without any text inputted) and going to the partners portal to see that it was stored correctly
b) submit a **paper** app to the same listing with a unique mix of demographic data also including empty other selections and then edit this paper app multiple times …
=> fix: handle empty other race options (#4513)

api/src/services/listing-csv-export.service.ts, api/test/unit/services/listing-csv-export.service.spec.ts
This PR addresses #1027 
The listing units csv export is displaying the incorrect AMI Chart percentage. It is grabbing the first value from the amiChart instead of getting the percentage off of the unit table
Note:
- There are currently no tests that cover the CSV export. I have added a test as part of this change, but only test the unit CSV. More tests should be added
After a clean reseed In the partner site click the "Export to CSV" button on the listings page and compare the values to the listings
- Either (1) explicitly ask a clarifying question, (2) request changes, or (3) approve the …
=> fix: use correct ami percentage in csv (#4520)

api/src/utilities/application-export-helpers.ts
This PR addresses [#(4536)](https://app.zenhub.com/workspaces/bloom-5dc32d7144bd400001315dac/issues/gh/bloom-housing/bloom/4536)
For preferences that required an address to be input, they were appearing for the application export but not for the lottery export. This adjustment allows it to work correctly for both.
On the partner site, create/update a listing to be a lottery listing with a preference that requires/allows for an address to be input.
Submit an application for the listing, claim the preference and include an address.
Export applications and verify the preference and preference address appear correctly.
Close the listing, run the lottery, export the lottery, and verify the preference and preference address appear correctly.
- Ensure the author …
=> release: include preference address (#4537)

api/src/utilities/unit-utilities.ts
This PR addresses #4631
The units summarization process was failing to handle multiple units without rent information. The first unit was correctly handled with "t.n/a" in the getDefaultSummary function but then from there the inputs to a minMax function were t.n/a and null leading to the NaN. This fix avoids the minMax comparison if the unit's associated field is null.
Add multiple units of the same unit type to a listing that have no rent or rent as a percentage of income information. Ensure that the unit summary displays with n/a rather than NaN per month.
- Either (1) explicitly ask a …
=> fix: null checks in minMax process (#4632)

sites/partners/cypress/e2e/default/03-listing.spec.ts, sites/partners/src/components/listings/PaperListingForm/UnitForm.tsx
(Looks like it did make its way into Doorway)
=> fix: prevent listings without AMI charts (#4169)

shared-helpers/src/locales/es.json, shared-helpers/src/locales/general.json, shared-helpers/src/locales/tl.json, shared-helpers/src/locales/vi.json, shared-helpers/src/locales/zh.json, sites/public/src/layouts/application.tsx
This PR addresses #4690
Adds a new maintenance message for the Alameda transition.
I tested the message locally by manually toggling maintenance mode to be on.
After this is merged, to turn this on in production, I will set the following variable on only the Alameda public site:
`MAINTENANCE_WINDOW=2025-03-12 00:00 -08:00,2025-05-12 00:00 -08:00`
=> feat: new maintenance message

api/prisma/seed-helpers/reserved-community-type-factory.ts, sites/public/cypress/e2e/account/account.spec.ts, sites/public/src/layouts/application.tsx
This PR addresses [issue with release](https://exygy.slack.com/archives/C01Q4QG5R8Q/p1745330669188909)
With the recent release there was an accidental removal of the Alameda banner. The maintenance banner is showing where the transition banner should. This is because when the Alameda transition banner was added it was added in place of the maintenance banner and a `MAINTENANCE_WINDOW` env variable was set. So when merge conflicts happened it was not noticed that the translation in that spot was incorrect.
This change keeps the maintenance banner the same and instead places the transition banner where it is supposed to be for Alameda 
* Locally set the jurisdiction to be `Alamaeda`
* Remove the `MAINTENANCE_WINDOW` env variable 
You should see the correct transition banner
You can also see …
=> fix: re-add the Alameda transition banner

shared-helpers/src/locales/es.json, shared-helpers/src/locales/general.json, shared-helpers/src/locales/tl.json, shared-helpers/src/locales/vi.json, shared-helpers/src/locales/zh.json, sites/public/.env.template, sites/public/next.config.js, sites/public/src/layouts/application.module.scss, sites/public/src/layouts/application.tsx
This PR releases #4846 with custom copy
This PR builds off of the maintenance banner pattern to include a generic site message. This way we can turn on the site message and maintenance banner simultaneously or toggle them more quickly with the env variables.
**Most importantly, this adds the updated AC transition banner copy**
Update the MAINTENANCE_WINDOW and SITE_MESSAGE_WINDOW env variables and rebuild to see the view when one, both, or neither are showing. NOTE: This functionality is not part of the seeds SiteHeader so seeds must be turned off
**Set your jurisdiction env var to Alameda to see the following updated copy** "This site will be moving to the Doorway Housing Portal, at [housingbayarea.org](http://housingbayarea.org/), starting on May 12th. To learn more about the changes, …
=> fix: customized site message

sites/partners/__tests__/components/applications/sections/FormAlternateContact.test.tsx, sites/partners/__tests__/components/applications/sections/FormApplicationData.test.tsx, sites/partners/__tests__/components/applications/sections/FormDemographics.test.tsx, sites/partners/__tests__/components/applications/sections/FormHouseholdDetails.test.tsx, sites/partners/__tests__/components/applications/sections/FormHouseholdIncome.test.tsx, sites/partners/__tests__/components/applications/sections/FormHouseholdMembers.test.tsx, sites/partners/__tests__/components/applications/sections/FormMultiselectQuestions.test.tsx, sites/partners/__tests__/components/applications/sections/FormPrimaryApplicant.test.tsx, sites/partners/__tests__/components/applications/sections/FormTerms.test.tsx, sites/partners/__tests__/components/applications/sections/helpers.tsx, sites/partners/__tests__/pages/listings/[id]/applications/add.test.tsx, sites/partners/src/components/applications/PaperApplicationForm/sections/FormApplicationData.tsx, sites/partners/src/components/applications/PaperApplicationForm/sections/FormPrimaryApplicant.tsx
This PR addresses #4572 
* Add integration tests for application form components 
* Add integration tests for the main use cases of the add new listing application page.
Run the unit test suite for the patterns page 
```
npm run test:app:partners:unit
```
=> 4572/listings application add integration tests 

sites/public/__tests__/pages/account/dashboard.test.tsx, sites/public/src/pages/account/dashboard.tsx
This PR addresses #4548
* Update the public site account dashboard component to use router hook pattern instead of HOC pattern 
* Add integration tests for the dashboard page content
Run the following command in the main directory
```
cd sites/public && yarn jest -w --verbose -t "<Dashboard>"
```
=> feat: public user dashboard integration tests 

api/src/dtos/auth/confirm.dto.ts, api/src/dtos/auth/update-password.dto.ts
This PR addresses [slack conversation](https://exygy.slack.com/archives/C03PB25AVTR/p1745414853923449)
There are no differences between core and HBA
On rare occasions confirmation tokens can be longer than 256 characters. This causes an issue when the user tries to confirm their account because we have a MaxLength of 256 on the token field
This was happening if the user account's email was extra long. You can test this by creating a user with a really long email
The confirmation and forget password flows should fully work
- Either (1) explicitly ask a clarifying question, (2) request changes, …
=> fix: remove token max length (#4833)

api/prisma/seed-helpers/feature-flag-factory.ts, api/src/services/listing.service.ts, api/test/integration/listing.e2e-spec.ts
This PR addresses #4751 
*NOTE*: this won't impact HBA but pulled over to keep the code in sync
The duplication (copy) of listings already works for listings that use unit groups instead of units. However, if you don't want to copy the units a small change was needed.
To Copy with units groups
* Seed the staging data
* open up one of the "lakeview" listings in the partner site
* Click "copy" for the listing
* Enter a new listing name and submit
* Verify the listing along with the unit groups were transferred.
To copy without unit groups
* Seed the staging data
* open up one of the "lakeview" listings in the partner site
* Click "copy" for the listing
* uncheck the "include units" checkbox
* Click submit
* Verify the listing was copied, but the unit groups were not
- Read and understand …
=> fix: allow duplication to not copy unit groups (bloom-housing#4823)

api/src/dtos/unit-groups/unit-group-summary.dto.ts, api/src/utilities/unit-groups-transformations.ts, api/test/unit/services/listing.service.spec.ts, api/test/unit/utilities/unit-group-transformations.spec.ts, shared-helpers/__tests__/views/summaryTables.test.ts, shared-helpers/src/locales/general.json, shared-helpers/src/types/backend-swagger.ts, shared-helpers/src/views/summaryTables.tsx, sites/public/src/components/browse/ListingCard.tsx, sites/public/src/components/listing/ListingViewSeeds.tsx, sites/public/src/components/listing/listing_sections/RentSummary.tsx, sites/public/src/lib/helpers.tsx
This PR addresses #4670 
Releases: https://github.com/bloom-housing/bloom/pull/4752
Adds table for unit groups for listing list, and for listing view.
To add unit groups use code from [this PR](https://github.com/bloom-housing/bloom/pull/4676) (just change `id`'s. and maybe add some more `unitGroupAmiLevels`)
on public site `/listings` It should summarize all unit groups to one row.
For listing view it should show it separate for each unit group
- Either (1) explicitly ask a clarifying question, (2) request changes, or (3) approve the PR, even if there are very small remaining changes, if you …
=> release: FE - public unit groups (#4752)

api/prisma/seed-helpers/unit-group-factory.ts, api/src/services/listing.service.ts, api/test/integration/listing.e2e-spec.ts, api/test/unit/services/listing.service.spec.ts
This PR addresses #4761 
Releases: https://github.com/bloom-housing/bloom/pull/4799
Adds missing filters for unit groups related fields. It doesn't include number of bathroom, as it's not present in detroit (and it's not really applicable).
For monthly rent it should work fine for single filters, but if it got double filters like greater than 2400 and less than 2600 it will return all listings. Not sure if we got any ways of handling that so i left it for now.
Also `monthlyRent` for `units` seem to be comparing strings not numbers so for example `9` is bigger than `1000`, again not sure if i'm missing something so left it.
seed data with unitGroups (it takes bedrooms from unitTypes, and monthlyRent from unitGroupAmiLevels.flatRentValue, also it will return that listing when …
=> release: add filters for unitGroups (#4799)

sites/public/.env.template, sites/public/next.config.js, sites/public/src/lib/hooks.ts
This PR addresses #4834 
* Remove separate environmental variables for max open and closed listings 
* Add a new generic listing browse environmental variable to maintain consistency between tabs
* Update listings fetcher hooks to use the new env variable
* Seed the application with a different number of closed and open applications 
* Turn on the Listings Pagination feature flag
* Visit the listings browser on public sites
* Adjust the new event variable to test the consistency of currently displayed listings in both `closed` and `open` paths
- Either (1) explicitly ask a clarifying …
=> fix: open + closed listings tab fix 

sites/partners/src/components/listings/PaperListingForm/index.tsx, sites/partners/src/components/listings/PaperListingForm/sections/Units.tsx
This PR addresses #4801 
* Update the existing codebase to reduce code repetition in favor of existing props and values
* Update the partners' site listing submission to conditionally clear existing `units`/`unit groups` based on the selected jurisdiction feature flags
Clearing the fields could also be moved inside the formatted class by passing the `enableUnitGroups` feature flag as metadata. This logic has been implemented outside of the formatter for clarity, but I'm open to discussing such an approach.
* Seed the database
* Go to the partners' site listings view and select a listing with unit groups currently enabled (ex., _Lakeview Villa_)
* Edit the listing by changing the jurisdiction to one where the unit group flag is disabled (ex., _Bloomington_)
* Save the changes. No error …
=> fix: jurisdiction unit groups bug fix (#4860)

sites/partners/src/components/listings/PaperListingForm/UnitGroupForm.tsx, sites/partners/src/components/listings/PaperListingForm/sections/Units.tsx, sites/partners/src/page_content/locale_overrides/general.json
This PR addresses #4917 
* Fix issue causing the unit groups to save and retrieve the `openWaitlist` values incorrectly
* Go to `/listings` on the partner's side
* Select one of the listings containing unit groups and click `Edit`
* Add a new unit group
* Verify the `Open Waitlist` section in the drawer is properly set on multiple re-openings of the drawer
=> fix: unit group closed waitlist bug

api/prisma/seed-helpers/listing-factory.ts
Updates the seed to always add a due date. Otherwise, we're unable to save seeded listings until we add a due date. There should be no visible changes.
=> fix: update seed with due date (#4979)

shared-helpers/package.json, sites/partners/package.json, sites/public/package.json, yarn.lock
Fixes a wrapping issue where waitlists with 4+ digits were wrapping onto multiple lines - does so by uptaking latest UIC.
From the core PR to see examples, you can compare [this listing on dev](https://bloom.exygy.dev/listing/cf908bad-5e0d-41ce-b688-f4be27408449/test_another_lottery_1233_w_main_chicago_il) to the [same listing on this deploy preview](https://deploy-preview-4935--bloom-exygy-dev.netlify.app/listing/cf908bad-5e0d-41ce-b688-f4be27408449/test_another_lottery_1233_w_main_chicago_il).
=> fix: five digit waitlist size (#4935)

shared-helpers/__tests__/views/summaryTables.test.ts, shared-helpers/src/views/summaryTables.tsx, sites/partners/src/components/listings/PaperListingForm/UnitGroupForm.tsx
Creates the ability to save a closed waitlist, and also shows it on the public site. This is only visible with unit groups on, so nothing should be visible.
=> fix: show closed waitlist (#4978)

api/src/enums/listings/view-enum.ts, api/src/services/listing.service.ts, api/test/unit/services/listing.service.spec.ts, shared-helpers/src/types/backend-swagger.ts, sites/partners/src/lib/hooks.ts, sites/partners/src/pages/users/index.tsx
Currently in our smallest testing dynos in Heroku, if we have a good number of listings (currently testing with over 300), you're unable to add a partner user. This is because we are fetching every single listing to be able to show the drawer that has checkboxes for each listing to give access. We are fetching much more data than we need to, and we're running out of memory.
We should instead fetch only the name, id, and jurisdiction.
To test, you should add a new partner user and ensure you can check and uncheck individual listings.
=> refactor: fetch less data in partner user drawer (#5014)

api/src/utilities/unit-groups-transformations.ts, api/test/unit/utilities/unit-group-transformations.spec.ts
This PR addresses #5034 
Updates the algorithms for sorting unit groups on the backend when listing is created/updated
* Make sure the `enableUnitGroups` feature flag has been turned on on the currently configured jurisdiction
* Go to the partner's sites dashboard and select any listing
* Update/Create a few unit groups with different unit types and ami percentages values (some unit types should be duplicated to test secondary sorting, example below)
* Save the listing with the new configuration 
* Go to the public sites `/listings` page and select the previously updated listing
* The rent section table should show properly sorted unit groups
- Pull the changes down …
=> feat: Update unitGroups sorting algorithm to secondary sort over ami percentage

shared-helpers/__tests__/views/summaryTables.test.ts, shared-helpers/src/views/summaryTables.tsx
This PR addresses #5048 
* Update the waitlist status label for closed status (the logic now mirrors one used on the details page)
* Make sure the `enableUnitGroups` flag is turned on for the jurisdiction currently configured in the .env file
* Make sure at least one listing has all unit groups `Waitlist Status` set to 'Closed'
* Go to the public sites "/listings" page
* Scroll to the listing configured in the second step
* The unit groups preview table on the listing card should say “Closed waitlist” instead of “Not available”
- Either (1) explicitly ask a clarifying question, (2) request …
=> fix: Fix search page waitlist status closed label bug  (#5073)

sites/partners/cypress/e2e/default/03-listing.spec.ts, sites/partners/cypress/e2e/default/04-application.spec.ts, sites/partners/cypress/e2e/default/05-paperApplication.spec.ts, sites/partners/cypress/e2e/default/06-admin-user-mangement.spec.ts, sites/partners/cypress/e2e/default/07-jurisdictional-admin-user-management.spec.ts, sites/partners/cypress/e2e/default/08-preference-management.spec.ts, sites/partners/cypress/e2e/default/09-lottery.spec.ts, sites/partners/cypress/e2e/listings-approval/listings-approval.spec.ts, sites/partners/cypress/support/commands.js, sites/partners/cypress/support/index.d.ts
This PR addresses #5086 
This PR removes the necessity of walking through the login page UI before starting each test. Instead authentication is handled via an api whenever the test is not explicitly testing the login functionality.
The goal of this change is to speed up and reduce flakiness of tests by removing unnecessary UI steps.
Changes were only made to the partner site tests. I believe it makes sense for the tests in the public site currently using a shared signin function to continue walking through the UI.
No functional changes introduced. All tests should continue to pass as before. …
=> test: auth with api when not testing sign in (#5108)

sites/partners/src/components/applications/PaperApplicationForm/sections/FormMultiselectQuestions.tsx, sites/public/src/pages/applications/financial/income.tsx, sites/public/src/pages/applications/start/choose-language.tsx
RELEASE
This PR partially addresses #4991 by fixing #5041 and #5040 
This PR adds three different null checks based on common application flow testing.
1. Currently the community types (programs under the hood) from Detroit prod have no options set. This will need to be handled by updating the data but as a partial step, I added a null check so the paper application form can load even with these listings attached to them.
2. Detroit prod data had {en} set for the languages field on the jurisdiction table. This resulted in no options appearing on the choose-language.tsx page. This check allows for one button to show.
3. Common app flows with unit groups were failing on the income step because of the verify income logic. This PR checks for units before verifying the income. I also made a …
=> fix: add null checks (#5055)
